// Generated by tools/compat/extract-schema.mjs from packages/schema/src/agent.ts at 7faf945 (Stratlas 0.8). Do not edit.
import { z } from 'zod';
export const ToolRisk = z.enum(['read', 'navigate', 'write', 'send']);
export const ToolScope = z.enum(['app', 'project', 'window']);
export const WindowKind = z.enum([
  'scene3d',
  'map',
  'video',
  'photo',
  'pointcloud',
  'report',
  'issues',
]);
export const AiProvider = z.enum(['anthropic', 'openai', 'google', 'local']);
export const AiTask = z.enum(['chat', 'vision', 'report', 'extract', 'build']);
export const AiErrorCode = z.enum(['anthropic-workspace']);
export const ToolMeta = z.object({
  name: z.string().regex(/^[a-z][a-z0-9_]{2,63}$/, 'Tool names are lower snake_case'),
  description: z.string().min(10),
  scope: ToolScope,
  risk: ToolRisk,
  windows: z.array(WindowKind).optional(),
});
export const needsApproval = (risk) => risk === 'write' || risk === 'send';
