// Generated by tools/compat/extract-schema.mjs from packages/schema/src/common.ts at 7faf945 (Stratlas 0.8). Do not edit.
import { z } from 'zod';
export const Id = z.string().min(1).max(128);
export const Vec2 = z.tuple([z.number(), z.number()]);
export const Vec3 = z.tuple([z.number(), z.number(), z.number()]);
export const Quat = z.tuple([z.number(), z.number(), z.number(), z.number()]);
export const Mat4 = z.array(z.number()).length(16);
export const IsoTime = z.iso.datetime({
  offset: true,
});
export const IsoDate = z.iso.date();
export const HexColor = z.string().regex(/^#[0-9a-fA-F]{6}$/, 'Colour must be #rrggbb');
export const AssetRef = z.union([
  z
    .object({
      hash: z.string().regex(/^[a-f0-9]{64}$/),
    })
    .strict(),
  z
    .object({
      path: z.string().min(1),
    })
    .strict(),
]);
export const ok = (value) => ({
  ok: true,
  value,
});
export const err = (error) => ({
  ok: false,
  error,
});
export function uniqueIds(key) {
  return (value, ctx) => {
    const seen = new Set();
    for (const item of value[key]) {
      if (seen.has(item.id)) {
        ctx.addIssue({
          code: 'custom',
          message: `Duplicate id "${item.id}" in ${key}`,
          path: [key],
        });
      }
      seen.add(item.id);
    }
  };
}
