// Generated by tools/compat/extract-schema.mjs from packages/schema/src/ipc.ts at 7faf945 (Stratlas 0.8). Do not edit.
import { z } from 'zod';
import { AiErrorCode, AiProvider, AiTask, ToolRisk, WindowKind } from './agent.mjs';
import { Issue } from './annotation.mjs';
import { Conversation, ConversationId, ConversationSummary } from './conversation.mjs';
import { JobEvent, JobId, JobLogLine, JobRecord, JobStartRequest, RuntimeInfo } from './jobs.mjs';
import {
  AltitudeChoice,
  AltitudePlan,
  ImportHeights,
  ImportItem,
  LayerPatch,
  NewProjectRequest,
  ReportBrand,
  SeverityTemplate,
} from './builder.mjs';
import { ProjectManifest } from './manifest.mjs';
import { HexColor } from './common.mjs';
import { AiPolicy, EditPolicy, ExportKind, PackageInfo, PackageOrigin } from './package.mjs';
import { BoundaryEditsFile, VolumesFile } from './volumes.mjs';
import { DetectionsFile } from './detections.mjs';
import { NarrativeFile, ReportContentsSettings } from './report.mjs';
import { ReleaseNotes, UpdateStatus } from './update.mjs';
import {
  ChangeKind,
  ChangeSet,
  ChangeSetId,
  ChangeSetSummary,
  ChangeThresholds,
} from './change.mjs';
import { ProcModel, ProcModelId, ProcModelSummary } from './procmodel.mjs';
import {
  DetectorModelId,
  DetectorModelInfo,
  InferenceItem,
  InferenceRuntime,
  InferenceSettings,
} from './inference.mjs';
const Empty = z.object({}).strict();
export const FailureCode = z.enum(['not-implemented', 'read-only']);
const Failure = z.object({
  ok: z.literal(false),
  error: z.string(),
  code: FailureCode.optional(),
});
const OkOrFailure = z.discriminatedUnion('ok', [
  z.object({
    ok: z.literal(true),
  }),
  Failure,
]);
const ProjectId = z.string().min(1);
export const DetectionPassName = z
  .string()
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,120}\.json$/, 'A pass file is a plain .json file name.');
export const DetectImage = z
  .object({
    key: z.string().min(1).max(300),
    dataUrl: z.string().startsWith('data:image/'),
    width: z.number().int().positive(),
    height: z.number().int().positive(),
  })
  .strict();
export const AiDetectionResult = z.object({
  classId: z.string(),
  label: z.string(),
  box: z.tuple([z.number(), z.number(), z.number(), z.number()]).optional(),
  polygon: z.array(z.tuple([z.number(), z.number()])).optional(),
  confidence: z.number().min(0).max(1).optional(),
  severity: z.number().int().nullable().optional(),
  uncertain: z.boolean().optional(),
  note: z.string().optional(),
});
export const LibraryEntry = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  customer: z.string().optional(),
  site: z.string().optional(),
  kind: z.enum(['native', 'aik', 'volumetric', 'road', 'twin']),
  sizeBytes: z.number().int().nonnegative().optional(),
  lastOpened: z.string().optional(),
  thumbnail: z.string().optional(),
  captureDate: z.string().optional(),
  layerCounts: z.record(z.string(), z.number().int().nonnegative()).optional(),
  package: z
    .object({
      encrypted: z.boolean(),
      readOnly: z.boolean(),
    })
    .optional(),
  demo: z
    .object({
      primary: z.boolean(),
    })
    .optional(),
});
export const SetupStatus = z.object({
  dataRoot: z.string(),
  dataRootExists: z.boolean(),
  mapPacks: z.number().int().nonnegative(),
  pipeline: z.object({
    found: z.boolean(),
    version: z.string().optional(),
    problem: z.string().optional(),
  }),
});
export const LocalModelSettings = z.object({
  enabled: z.boolean(),
  baseUrl: z.url({
    protocol: /^https?$/,
  }),
  model: z.string().min(1).max(200),
  kind: z.enum(['ollama', 'openai-compatible']).optional(),
  contextTokens: z.number().int().min(512).max(10_000_000).optional(),
  toolProfile: z.enum(['full', 'compact']).optional(),
  capabilities: z
    .object({
      tools: z.boolean(),
      vision: z.boolean(),
    })
    .strict()
    .optional(),
  timeoutMs: z.number().int().min(1000).max(3_600_000).optional(),
});
export const LocalModelInfo = z.object({
  id: z.string().min(1).max(200),
  name: z.string().optional(),
  sizeBytes: z.number().int().nonnegative().optional(),
  contextTokens: z.number().int().positive().optional(),
  tools: z.boolean().optional(),
  vision: z.boolean().optional(),
  family: z.string().optional(),
  quantization: z.string().optional(),
});
export const ModelRouteSchema = z.object({
  task: AiTask,
  provider: AiProvider,
  model: z.string().min(1),
});
export const ProviderUsage = z.object({
  provider: z.string().min(1),
  inputTokens: z.number().nonnegative(),
  outputTokens: z.number().nonnegative(),
  costUsd: z.number().nonnegative(),
  costKnown: z.boolean(),
});
export const ProjectUsage = z.object({
  key: z.string(),
  name: z.string(),
  updatedAt: z.string(),
  providers: z.array(ProviderUsage),
});
export const ReportBrandingSettings = z.object({
  companyName: z.string().max(120).optional(),
  accent: HexColor.optional(),
  logo: z
    .string()
    .regex(/^logo-[a-z0-9]{6,64}\.(png|jpg|svg)$/)
    .optional(),
});
export const CrashNotice = z.object({
  kind: z.enum(['closed', 'window']),
  report: z.string(),
  time: z.string(),
  process: z.string(),
  reason: z.string(),
});
const OptionalUrl = z.union([
  z.literal(''),
  z.url({
    protocol: /^https?$/,
  }),
]);
export const Settings = z.object({
  cloudAi: z.boolean(),
  theme: z.enum(['dark', 'light', 'system']),
  sidebarCollapsed: z.boolean(),
  dataRoot: z.string(),
  routes: z.array(ModelRouteSchema),
  localModel: LocalModelSettings.optional(),
  direction: z.enum(['ltr', 'rtl']).optional(),
  contrast: z.enum(['system', 'more']).optional(),
  motion: z.enum(['system', 'reduce']).optional(),
  offlineOnly: z.boolean().optional(),
  updateCheck: z.boolean().optional(),
  updateUrl: OptionalUrl.optional(),
  anthropicWorkspaceId: z
    .string()
    .trim()
    .max(128)
    .regex(/^[A-Za-z0-9_-]*$/, 'A workspace ID has only letters, digits, _ and -.')
    .optional(),
  reportBranding: ReportBrandingSettings.optional(),
  reportContents: ReportContentsSettings.optional(),
  change: ChangeThresholds.optional(),
  inference: InferenceSettings.optional(),
});
export const Bbox = z
  .tuple([
    z.number().min(-180).max(180),
    z.number().min(-90).max(90),
    z.number().min(-180).max(180),
    z.number().min(-90).max(90),
  ])
  .refine(([w, s, e, n]) => w < e && s < n, 'The box must have west < east and south < north');
const PackId = z.string().regex(/^[a-z0-9-]+$/);
export const MapPackInfo = z.object({
  id: PackId,
  label: z.string(),
  bbox: z.tuple([z.number(), z.number(), z.number(), z.number()]),
  maxZoom: z.number().int(),
  sizeBytes: z.number().int().nonnegative(),
  builtAt: z.string().optional(),
  source: z.enum(['download', 'import', 'build-tool', 'package']).optional(),
  build: z.string().optional(),
});
export const PackRegion = z.object({
  id: PackId.min(1).max(48),
  label: z.string().min(1).max(80),
  bbox: Bbox,
  maxZoom: z.number().int().min(0).max(15),
});
export const PackJob = PackRegion.extend({
  state: z.enum(['running', 'verifying', 'done', 'failed', 'cancelled', 'interrupted']),
  progress: z.number().min(0).max(1),
  bytes: z.number().int().nonnegative().optional(),
  error: z.string().optional(),
  startedAt: z.string(),
  build: z.string().optional(),
});
const Ok = z.object({
  ok: z.boolean(),
  error: z.string().optional(),
});
const OpenResult = z.discriminatedUnion('ok', [
  z.object({
    ok: z.literal(true),
    id: z.string(),
    root: z.string(),
    manifest: ProjectManifest,
    issues: z.array(Issue),
    package: PackageInfo.optional(),
    origin: PackageOrigin.optional(),
  }),
  z.object({
    ok: z.literal(false),
    error: z.string(),
    needsPassphrase: z.boolean().optional(),
  }),
]);
export const PackagePlan = z.object({
  layers: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      kind: z.string(),
      bytes: z.number().int().nonnegative(),
      files: z.number().int().nonnegative(),
    }),
  ),
  baseBytes: z.number().int().nonnegative(),
  totalBytes: z.number().int().nonnegative(),
  totalFiles: z.number().int().nonnegative(),
  freeBytes: z.number().int().nonnegative().optional(),
  mapPack: z
    .discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        sourceId: z.string(),
        sourceLabel: z.string(),
        bbox: z.tuple([z.number(), z.number(), z.number(), z.number()]),
        maxZoom: z.number().int(),
        bytes: z.number().int().nonnegative(),
        tiles: z.number().int().nonnegative(),
      }),
      z.object({
        ok: z.literal(false),
        reason: z.string(),
      }),
    ])
    .optional(),
});
export const PackageMapPackRequest = z
  .object({
    maxZoom: z.number().int().min(0).max(15),
    marginKm: z.number().min(0).max(100),
  })
  .strict();
export const PackageExportOptions = z
  .object({
    projectId: z.string().min(1),
    exclude: z.array(z.string()),
    readOnly: z.boolean(),
    aiPolicy: AiPolicy,
    editPolicy: EditPolicy.optional(),
    mapPack: PackageMapPackRequest.optional(),
    exports: z.array(ExportKind),
    passphrase: z.string().min(8).max(256).optional(),
    welcome: z
      .object({
        message: z.string().max(2000).optional(),
        tips: z.array(z.string().min(1).max(200)).max(8).optional(),
      })
      .optional(),
  })
  .strict();
export const EXPORT_FORMATS = [
  'csv',
  'geojson',
  'coco',
  'kit-json',
  'masks-zip',
  'report-pdf',
  'house-pdf',
];
export const ExportFormat = z.enum(EXPORT_FORMATS);
export const EXPORT_FORMAT_KIND = {
  csv: 'issues-csv',
  geojson: 'issues-geojson',
  coco: 'kit-json',
  'kit-json': 'kit-json',
  'masks-zip': 'masks',
  'report-pdf': 'report-pdf',
  'house-pdf': 'report-pdf',
};
export const ReportFile = z.object({
  path: z.string().min(1),
  name: z.string().min(1),
  sizeBytes: z.number().int().nonnegative(),
});
export const ChatMessage = z.object({
  role: z.enum(['user', 'assistant']),
  content: z.string(),
});
export const LicenseEntry = z.object({
  name: z.string(),
  version: z.string(),
  license: z.string(),
  homepage: z.string().optional(),
  author: z.string().optional(),
});
const VerifyResult = z.discriminatedUnion('ok', [
  z.object({
    ok: z.literal(true),
    version: z.string(),
    current: z.string(),
    signer: z.string(),
  }),
  z.object({
    ok: z.literal(false),
    error: z.string(),
  }),
]);
export const ipc = {
  'app:getInfo': {
    request: Empty,
    response: z.object({
      name: z.string(),
      version: z.string(),
      platform: z.string(),
      user: z.string().optional(),
    }),
  },
  'library:list': {
    request: Empty,
    response: z.array(LibraryEntry),
  },
  'app:setupStatus': {
    request: Empty,
    response: SetupStatus,
  },
  'library:add': {
    request: z
      .object({
        path: z.string().min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        entry: LibraryEntry,
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'project:open': {
    request: z
      .object({
        path: z.string().min(1),
        passphrase: z.string().min(1).max(256).optional(),
      })
      .strict(),
    response: OpenResult,
  },
  'project:writeIssues': {
    request: z
      .object({
        projectId: z.string().min(1),
        issues: z.array(Issue),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'project:readVolumes': {
    request: z
      .object({
        projectId: z.string().min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        volumes: VolumesFile.nullable(),
        edits: BoundaryEditsFile.nullable(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'project:writeBoundaries': {
    request: z
      .object({
        projectId: z.string().min(1),
        file: BoundaryEditsFile,
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'project:writeCentreline': {
    request: z
      .object({
        projectId: z.string().min(1),
        coordinates: z
          .array(z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]))
          .min(2)
          .max(20000),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        path: z.string(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'packs:list': {
    request: Empty,
    response: z.array(MapPackInfo),
  },
  'packs:download': {
    request: PackRegion.strict(),
    response: Ok,
  },
  'packs:jobs': {
    request: Empty,
    response: z.array(PackJob),
  },
  'packs:cancel': {
    request: z
      .object({
        id: PackId,
      })
      .strict(),
    response: Ok,
  },
  'packs:resume': {
    request: z
      .object({
        id: PackId,
      })
      .strict(),
    response: Ok,
  },
  'packs:dismiss': {
    request: z
      .object({
        id: PackId,
      })
      .strict(),
    response: Ok,
  },
  'packs:remove': {
    request: z
      .object({
        id: PackId,
      })
      .strict(),
    response: Ok,
  },
  'packs:import': {
    request: z
      .object({
        path: z.string().min(1),
        label: z.string().min(1).max(80).optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        pack: MapPackInfo,
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'settings:get': {
    request: Empty,
    response: Settings,
  },
  'settings:set': {
    request: Settings.partial().strict(),
    response: Settings,
  },
  'ai:setKey': {
    request: z
      .object({
        provider: AiProvider,
        key: z.string().min(8),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'ai:hasKey': {
    request: z
      .object({
        provider: AiProvider,
      })
      .strict(),
    response: z.object({
      present: z.boolean(),
    }),
  },
  'ai:testConnection': {
    request: z
      .object({
        provider: AiProvider,
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      message: z.string(),
      model: z.string().optional(),
      status: z.number().int().optional(),
      code: AiErrorCode.optional(),
    }),
  },
  'ai:send': {
    request: z
      .object({
        runId: z.string().min(1),
        projectId: z.string().min(1).optional(),
        window: WindowKind,
        context: z.record(z.string(), z.unknown()),
        messages: z.array(ChatMessage).min(1),
        image: z.string().startsWith('data:image/').optional(),
        task: AiTask.optional(),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'ai:toolResult': {
    request: z
      .object({
        runId: z.string().min(1),
        callId: z.string().min(1),
        approved: z.boolean(),
        result: z.unknown().optional(),
        error: z.string().optional(),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'ai:cancel': {
    request: z
      .object({
        runId: z.string().min(1),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'ai:status': {
    request: z
      .object({
        projectId: z.string().min(1).optional(),
        task: AiTask.optional(),
      })
      .strict(),
    response: z.object({
      ready: z.boolean(),
      reason: z
        .enum([
          'cloud-off',
          'no-key',
          'forbidden',
          'no-provider',
          'no-route',
          'local-off',
          'answer-only',
        ])
        .optional(),
      message: z.string().optional(),
      route: ModelRouteSchema.optional(),
      cloud: z.boolean(),
    }),
  },
  'ai:detect': {
    request: z
      .object({
        runId: z.string().min(1),
        projectId: z.string().min(1),
        classes: z
          .array(
            z
              .object({
                id: z.string().min(1),
                label: z.string().min(1),
              })
              .strict(),
          )
          .min(1)
          .max(300),
        severity: z
          .object({
            levels: z
              .array(
                z
                  .object({
                    value: z.number().int(),
                    label: z.string(),
                    criteria: z.string().optional(),
                  })
                  .strict(),
              )
              .max(20),
            uncertain: z.boolean().optional(),
          })
          .strict()
          .optional(),
        hint: z.string().max(2000).optional(),
        images: z.array(DetectImage).min(1).max(8),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        provider: z.string(),
        model: z.string(),
        promptVersion: z.string(),
        results: z.array(
          z.object({
            key: z.string(),
            detections: z.array(AiDetectionResult),
          }),
        ),
        inputTokens: z.number().nonnegative(),
        outputTokens: z.number().nonnegative(),
        costUsd: z.number().nonnegative().optional(),
        warnings: z.array(z.string()),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
        status: z.number().int().optional(),
        stopped: z.boolean().optional(),
      }),
    ]),
  },
  'detections:read': {
    request: z
      .object({
        projectId: z.string().min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        files: z.array(
          z.object({
            name: DetectionPassName,
            file: DetectionsFile,
          }),
        ),
        problems: z.array(
          z.object({
            name: z.string(),
            error: z.string(),
          }),
        ),
        sizes: z.record(z.string(), z.tuple([z.number(), z.number()])),
        issuesMap: z.record(z.string(), z.array(z.string())),
        readOnly: z.boolean(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'detections:write': {
    request: z
      .object({
        projectId: z.string().min(1),
        name: DetectionPassName,
        file: DetectionsFile,
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'detections:maskAssistStatus': {
    request: Empty,
    response: z.object({
      available: z.boolean(),
      model: z.string().optional(),
      reason: z.enum(['no-model', 'no-runtime', 'failed']).optional(),
      detail: z.string().optional(),
    }),
  },
  'detections:maskAssist': {
    request: z
      .object({
        projectId: z.string().min(1),
        path: z.string().min(1),
        box: z.tuple([z.number(), z.number(), z.number().positive(), z.number().positive()]),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        points: z.array(z.tuple([z.number(), z.number()])).min(3),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'ai:project': {
    request: z
      .object({
        projectId: z.string().min(1),
      })
      .strict(),
    response: z.object({
      alwaysAllow: z.boolean(),
      policy: AiPolicy,
      usage: z.array(ProviderUsage),
      cloudDrawings: z.boolean().optional(),
    }),
  },
  'ai:setConsent': {
    request: z
      .object({
        projectId: z.string().min(1),
        alwaysAllow: z.boolean(),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'ai:usage': {
    request: Empty,
    response: z.object({
      projects: z.array(ProjectUsage),
    }),
  },
  'ai:listConversations': {
    request: z
      .object({
        projectId: z.string().min(1),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      conversations: z.array(ConversationSummary),
      error: z.string().optional(),
    }),
  },
  'ai:loadConversation': {
    request: z
      .object({
        projectId: z.string().min(1),
        id: ConversationId,
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      conversation: Conversation.optional(),
      error: z.string().optional(),
    }),
  },
  'ai:saveConversation': {
    request: z
      .object({
        projectId: z.string().min(1),
        conversation: Conversation,
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'dialog:openFolder': {
    request: z
      .object({
        title: z.string().optional(),
      })
      .strict(),
    response: z.object({
      path: z.string().nullable(),
    }),
  },
  'dialog:saveFile': {
    request: z
      .object({
        defaultName: z.string().min(1).max(255),
        data: z.union([z.string(), z.instanceof(Uint8Array)]),
        title: z.string().optional(),
      })
      .strict(),
    response: z.object({
      path: z.string().nullable(),
      error: z.string().optional(),
    }),
  },
  'dialog:openFile': {
    request: z
      .object({
        title: z.string().optional(),
        filters: z
          .array(
            z.object({
              name: z.string(),
              extensions: z.array(z.string().min(1)),
            }),
          )
          .optional(),
      })
      .strict(),
    response: z.object({
      path: z.string().nullable(),
    }),
  },
  'app:takeOpenPath': {
    request: Empty,
    response: z.object({
      path: z.string().nullable(),
    }),
  },
  'package:plan': {
    request: z
      .object({
        projectId: z.string().min(1),
        exclude: z.array(z.string()),
        mapPack: PackageMapPackRequest.optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        plan: PackagePlan,
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'package:export': {
    request: z
      .object({
        jobId: z.string().min(1),
        options: PackageExportOptions,
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        path: z.string().nullable(),
        bytes: z.number().optional(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'package:cancel': {
    request: z
      .object({
        jobId: z.string().min(1),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'package:extract': {
    request: z
      .object({
        jobId: z.string().min(1),
        projectId: z.string().min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        root: z.string().nullable(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'export:run': {
    request: z
      .object({
        jobId: z.string().min(1).max(64),
        projectId: z.string().min(1),
        format: ExportFormat,
        issueIds: z.array(z.string().min(1)).optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        path: z.string().nullable(),
        count: z.number().int().nonnegative().optional(),
        bytes: z.number().int().nonnegative().optional(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'dialog:openFiles': {
    request: z
      .object({
        title: z.string().optional(),
        filters: z
          .array(
            z.object({
              name: z.string(),
              extensions: z.array(z.string().min(1)),
            }),
          )
          .optional(),
        multi: z.boolean().optional(),
      })
      .strict(),
    response: z.object({
      paths: z.array(z.string()),
    }),
  },
  'builder:templates': {
    request: Empty,
    response: z.object({
      severity: z.array(SeverityTemplate),
      brands: z.array(ReportBrand),
    }),
  },
  'builder:createProject': {
    request: NewProjectRequest,
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        path: z.string(),
        manifest: ProjectManifest,
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'builder:photoGps': {
    request: z
      .object({
        path: z.string().min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        lon: z.number(),
        lat: z.number(),
        alt: z.number().optional(),
        altFrom: z.enum(['takeoff', 'photo']).optional(),
        takenAt: z.string().optional(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'export:cancel': {
    request: z
      .object({
        jobId: z.string().min(1).max(64),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'branding:setLogo': {
    request: z
      .object({
        path: z.string().min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        settings: Settings,
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'branding:clearLogo': {
    request: Empty,
    response: Settings,
  },
  'thumbs:put': {
    request: z
      .object({
        projectId: z.string().min(1),
        path: z.string().min(1).max(1024),
        data: z.instanceof(Uint8Array).refine((d) => d.byteLength <= 512 * 1024, {
          message: 'Thumbnail is larger than 512 KB',
        }),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'report:list': {
    request: z
      .object({
        projectId: z.string().min(1),
      })
      .strict(),
    response: z.object({
      files: z.array(ReportFile),
    }),
  },
  'report:readNarrative': {
    request: z
      .object({
        projectId: z.string().min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        file: NarrativeFile.nullable(),
        readOnly: z.boolean(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'report:writeNarrative': {
    request: z
      .object({
        projectId: z.string().min(1),
        file: NarrativeFile,
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'ai:draftText': {
    request: z
      .object({
        runId: z.string().min(1).max(64),
        projectId: z.string().min(1),
        task: AiTask,
        system: z.string().min(1).max(20_000),
        prompt: z.string().min(1).max(200_000),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        text: z.string(),
        provider: z.string(),
        model: z.string(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'app:about': {
    request: Empty,
    response: z.object({
      version: z.string(),
      electron: z.string(),
      chrome: z.string(),
      node: z.string(),
      platform: z.string(),
      arch: z.string(),
      dataRoot: z.string(),
      userData: z.string(),
      logsDir: z.string(),
      packaged: z.boolean(),
      store: z.boolean().optional(),
    }),
  },
  'app:licenses': {
    request: Empty,
    response: z.array(LicenseEntry),
  },
  'app:exportLogs': {
    request: Empty,
    response: z.object({
      path: z.string().nullable(),
      error: z.string().optional(),
    }),
  },
  'app:showFolder': {
    request: z
      .object({
        which: z.enum(['data', 'logs', 'userData']),
      })
      .strict(),
    response: Ok,
  },
  'app:exportDiagnostics': {
    request: z
      .object({
        problem: z
          .object({
            what: z.string().max(8000),
            steps: z.string().max(8000).optional(),
          })
          .strict()
          .optional(),
        graphics: z
          .object({
            tier: z.string().max(20),
            detected: z.string().max(20),
            override: z.string().max(20).nullable(),
            renderer: z.string().max(500).nullable(),
            report: z
              .record(
                z.string().max(40),
                z.union([
                  z.string().max(500),
                  z.number(),
                  z.boolean(),
                  z.null(),
                  z.array(z.string().max(40)).max(20),
                ]),
              )
              .optional(),
          })
          .strict()
          .optional(),
        openProject: z.string().max(200).optional(),
      })
      .strict(),
    response: z.object({
      path: z.string().nullable(),
      error: z.string().optional(),
    }),
  },
  'app:crashNotice': {
    request: Empty,
    response: z.object({
      notice: CrashNotice.nullable(),
    }),
  },
  'app:dismissCrashNotice': {
    request: Empty,
    response: Ok,
  },
  'update:verifyFile': {
    request: z
      .object({
        path: z.string().min(1),
      })
      .strict(),
    response: VerifyResult,
  },
  'update:installFile': {
    request: z
      .object({
        path: z.string().min(1),
      })
      .strict(),
    response: Ok,
  },
  'update:check': {
    request: Empty,
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        available: z.boolean(),
        version: z.string().optional(),
        notes: z.string().optional(),
        size: z.number().optional(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'update:downloadAndInstall': {
    request: Empty,
    response: Ok,
  },
  'update:notes': {
    request: Empty,
    response: ReleaseNotes,
  },
  'update:status': {
    request: Empty,
    response: UpdateStatus,
  },
  'update:rollback': {
    request: Empty,
    response: Ok,
  },
  'app:rendererReady': {
    request: Empty,
    response: Ok,
  },
  'jobs:start': {
    request: JobStartRequest,
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        job: JobRecord,
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'jobs:list': {
    request: Empty,
    response: z.object({
      runtime: RuntimeInfo,
      jobs: z.array(JobRecord),
    }),
  },
  'jobs:cancel': {
    request: z
      .object({
        jobId: JobId,
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'jobs:log': {
    request: z
      .object({
        jobId: JobId,
        tail: z.number().int().min(1).max(5000).optional(),
      })
      .strict(),
    response: z.object({
      lines: z.array(JobLogLine),
    }),
  },
  'jobs:open': {
    request: z
      .object({
        jobId: JobId,
        what: z.enum(['output', 'log', 'project']),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'builder:import': {
    request: z
      .object({
        projectId: z.string().min(1),
        paths: z.array(z.string().min(1)).min(1),
        utcOffsetMin: z.number().int().min(-720).max(840).optional(),
        altitude: AltitudeChoice.optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        manifest: ProjectManifest,
        items: z.array(ImportItem),
        heights: ImportHeights.optional(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
        items: z.array(ImportItem).optional(),
      }),
    ]),
  },
  'builder:altitudePlan': {
    request: z
      .object({
        projectId: z.string().min(1),
        paths: z.array(z.string().min(1)).min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        plan: AltitudePlan,
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'builder:updateLayers': {
    request: z
      .object({
        projectId: z.string().min(1),
        layerIds: z.array(z.string().min(1)).min(1),
        patch: LayerPatch,
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        manifest: ProjectManifest,
        backup: z.string(),
      }),
      z.object({
        ok: z.literal(false),
        error: z.string(),
      }),
    ]),
  },
  'change:list': {
    request: z
      .object({
        projectId: ProjectId,
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        sets: z.array(ChangeSetSummary),
        problems: z.array(
          z.object({
            name: z.string(),
            error: z.string(),
          }),
        ),
        readOnly: z.boolean(),
      }),
      Failure,
    ]),
  },
  'change:read': {
    request: z
      .object({
        projectId: ProjectId,
        id: ChangeSetId,
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        set: ChangeSet,
        readOnly: z.boolean(),
      }),
      Failure,
    ]),
  },
  'change:write': {
    request: z
      .object({
        projectId: ProjectId,
        set: ChangeSet,
      })
      .strict(),
    response: OkOrFailure,
  },
  'change:compute': {
    request: z
      .object({
        jobId: z.string().min(1).max(64),
        projectId: ProjectId,
        from: z.string().min(1),
        to: z.string().min(1),
        kinds: z.array(ChangeKind).min(1),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        ids: z.array(ChangeSetId),
      }),
      Failure,
    ]),
  },
  'change:cancel': {
    request: z
      .object({
        jobId: z.string().min(1).max(64),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'model:list': {
    request: z
      .object({
        projectId: ProjectId,
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        models: z.array(ProcModelSummary),
        readOnly: z.boolean(),
      }),
      Failure,
    ]),
  },
  'model:read': {
    request: z
      .object({
        projectId: ProjectId,
        id: ProcModelId,
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        model: ProcModel,
        readOnly: z.boolean(),
      }),
      Failure,
    ]),
  },
  'model:write': {
    request: z
      .object({
        projectId: ProjectId,
        model: ProcModel,
      })
      .strict(),
    response: OkOrFailure,
  },
  'model:build': {
    request: z
      .object({
        projectId: ProjectId,
        id: ProcModelId,
        draft: z.boolean().optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        layer: z.string(),
        glb: z.string(),
      }),
      Failure,
    ]),
  },
  'ai:setCloudDrawings': {
    request: z
      .object({
        projectId: ProjectId,
        allow: z.boolean(),
      })
      .strict(),
    response: OkOrFailure,
  },
  'inference:models': {
    request: Empty,
    response: z.object({
      runtime: InferenceRuntime,
      models: z.array(DetectorModelInfo),
    }),
  },
  'inference:importModel': {
    request: z
      .object({
        path: z.string().min(1),
        acceptLicence: z.boolean(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        model: DetectorModelInfo,
      }),
      Failure,
    ]),
  },
  'inference:removeModel': {
    request: z
      .object({
        id: DetectorModelId,
      })
      .strict(),
    response: OkOrFailure,
  },
  'inference:run': {
    request: z
      .object({
        runId: z.string().min(1).max(64),
        projectId: ProjectId,
        model: DetectorModelId,
        items: z.array(InferenceItem).min(1).max(100_000),
        classMap: z.record(z.string(), z.string()),
        minConfidence: z.number().min(0).max(1),
        tile: z
          .object({
            size: z.number().int().min(64).max(8192),
            overlap: z.number().int().min(0).max(4096),
          })
          .strict()
          .optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        file: z.string(),
        count: z.number().int().nonnegative(),
      }),
      Failure,
    ]),
  },
  'inference:cancel': {
    request: z
      .object({
        runId: z.string().min(1).max(64),
      })
      .strict(),
    response: z.object({
      ok: z.boolean(),
    }),
  },
  'ai:localModels': {
    request: z
      .object({
        baseUrl: z
          .url({
            protocol: /^https?$/,
          })
          .optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        server: z
          .object({
            kind: z.enum(['ollama', 'openai-compatible']),
            version: z.string().optional(),
          })
          .optional(),
        models: z.array(LocalModelInfo),
      }),
      Failure,
    ]),
  },
  'ai:localProbe': {
    request: z
      .object({
        model: z.string().min(1).max(200),
        baseUrl: z
          .url({
            protocol: /^https?$/,
          })
          .optional(),
      })
      .strict(),
    response: z.discriminatedUnion('ok', [
      z.object({
        ok: z.literal(true),
        tools: z.boolean(),
        vision: z.boolean(),
        contextTokens: z.number().int().positive().optional(),
        latencyMs: z.number().nonnegative(),
      }),
      Failure,
    ]),
  },
};
export const ipcEvents = {
  'jobs:event': JobEvent,
  'ai:event': z.discriminatedUnion('type', [
    z.object({
      type: z.literal('text'),
      runId: z.string(),
      delta: z.string(),
    }),
    z.object({
      type: z.literal('tool-call'),
      runId: z.string(),
      callId: z.string(),
      name: z.string(),
      input: z.unknown(),
      risk: ToolRisk,
    }),
    z.object({
      type: z.literal('usage'),
      runId: z.string(),
      inputTokens: z.number(),
      outputTokens: z.number(),
      costUsd: z.number().optional(),
      provider: z.string().optional(),
      model: z.string().optional(),
    }),
    z.object({
      type: z.literal('done'),
      runId: z.string(),
    }),
    z.object({
      type: z.literal('error'),
      runId: z.string(),
      message: z.string(),
      code: AiErrorCode.optional(),
    }),
  ]),
  'package:progress': z.object({
    jobId: z.string(),
    bytesDone: z.number().nonnegative(),
    bytesTotal: z.number().nonnegative(),
    filesDone: z.number().int().nonnegative(),
    filesTotal: z.number().int().nonnegative(),
    current: z.string().optional(),
  }),
  'app:reportProblem': z.object({}).strict(),
  'app:openPath': z.object({
    path: z.string().min(1),
  }),
  'app:menu': z.object({
    action: z.enum(['settings', 'palette', 'guide', 'exportDiagnostics']),
  }),
  'update:progress': z.object({
    received: z.number().nonnegative(),
    total: z.number().nonnegative(),
    phase: z.enum(['download', 'verify', 'keep', 'install']),
  }),
  'export:progress': z.object({
    jobId: z.string(),
    phase: z.string(),
    done: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
  }),
  'packs:job': PackJob,
  'builder:progress': z.object({
    projectId: z.string(),
    done: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
    file: z.string(),
  }),
  'change:progress': z.object({
    jobId: z.string(),
    phase: z.string(),
    done: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
  }),
  'inference:progress': z.object({
    runId: z.string(),
    done: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
    found: z.number().int().nonnegative(),
    current: z.string().optional(),
  }),
};
