// Generated by tools/compat/extract-schema.mjs from packages/schema/src/manifest.ts at 7faf945 (Stratlas 0.8). Do not edit.
import { z } from 'zod';
import { Id, IsoDate, Vec3, err, ok, uniqueIds } from './common.mjs';
import { Layer } from './layers.mjs';
import { ClassCatalogue, SeverityModel } from './severity.mjs';
import { ProjectType, VerticalDatum } from './builder.mjs';
export const SCHEMA_VERSION = 'aio.project/1';
export const Capture = z.object({
  id: Id,
  label: z.string().min(1),
  date: IsoDate,
});
export const Crs = z.union([
  z
    .object({
      epsg: z.number().int(),
    })
    .strict(),
  z
    .object({
      wkt: z.string().min(1),
    })
    .strict(),
]);
export const ProjectManifest = z
  .object({
    schema: z.literal(SCHEMA_VERSION),
    id: Id,
    name: z.string().min(1),
    customer: z.string().optional(),
    site: z.string().optional(),
    crs: Crs,
    origin: Vec3,
    captures: z.array(Capture),
    layers: z.array(Layer),
    severityModels: z.array(SeverityModel),
    classCatalogues: z.array(ClassCatalogue),
    brand: z.string().optional(),
    type: ProjectType.optional(),
    verticalDatum: VerticalDatum.optional(),
    aiCloudDrawings: z.boolean().optional(),
  })
  .superRefine(uniqueIds('layers'))
  .superRefine(uniqueIds('severityModels'))
  .superRefine(uniqueIds('captures'));
export function parseManifest(json) {
  if (typeof json !== 'object' || json === null)
    return err('Project manifest is not a JSON object.');
  const version = json.schema;
  if (
    typeof version === 'string' &&
    version !== SCHEMA_VERSION &&
    version.startsWith('aio.project/')
  ) {
    return err(
      `Project was saved by a newer Stratlas (schema ${version}). Update the app to open it.`,
    );
  }
  const r = ProjectManifest.safeParse(json);
  if (r.success) return ok(r.data);
  const first = r.error.issues[0];
  const where = first?.path.length ? ` at ${first.path.join('.')}` : '';
  return err(`Project manifest is invalid${where}: ${first?.message ?? 'unknown error'}`);
}
