// Generated by tools/compat/extract-schema.mjs from packages/schema/src/package.ts at 7faf945 (Stratlas 0.8). Do not edit.
import { z } from 'zod';
import { Id, IsoTime, err, ok } from './common.mjs';
export const PACKAGE_SCHEMA = 'aio.package/1';
export const PACKAGE_HEADER_FILE = 'aio-package.json';
export const PACKAGE_EXTENSION = '.aio';
export const ExportKind = z.enum([
  'issues-csv',
  'issues-geojson',
  'report-pdf',
  'snapshot',
  'kit-json',
  'masks',
  'files',
]);
export const AiPolicy = z.enum(['forbid', 'allow']);
export const EditPolicy = z.enum(['forbid', 'allow']);
export const EMBEDDED_PACKS_DIR = 'packs';
export const PACKAGE_ORIGIN_FILE = 'package-origin.json';
export const DEFAULT_PACKAGE_EXPORTS = ['issues-csv', 'report-pdf', 'snapshot'];
export const PackageHeader = z.object({
  schema: z.literal(PACKAGE_SCHEMA),
  projectId: Id,
  createdAt: IsoTime,
  createdBy: z.string().optional(),
  readOnly: z.boolean().default(true),
  aiPolicy: AiPolicy.default('forbid'),
  editPolicy: EditPolicy.optional(),
  exports: z.array(ExportKind).default([...DEFAULT_PACKAGE_EXPORTS]),
  excludedLayers: z.array(Id).default([]),
  welcome: z
    .object({
      message: z.string().max(2000).optional(),
      tips: z.array(z.string().min(1).max(200)).max(8).optional(),
    })
    .optional(),
});
export const PackageInfo = z.object({
  header: PackageHeader,
  file: z.string(),
  encrypted: z.boolean(),
  sizeBytes: z.number().int().nonnegative(),
});
export const PackageOrigin = z.object({
  schema: z.literal('aio.origin/1'),
  package: z.string().min(1),
  path: z.string().optional(),
  projectId: Id,
  exportedAt: IsoTime,
  exportedBy: z.string().optional(),
  extractedAt: IsoTime,
  extractedBy: z.string().optional(),
  encrypted: z.boolean(),
});
export function packageEditAllowed(header) {
  return header.editPolicy === undefined ? !header.readOnly : header.editPolicy === 'allow';
}
export function parsePackageHeader(json) {
  if (typeof json !== 'object' || json === null) return err('Package header is not a JSON object.');
  const version = json.schema;
  if (
    typeof version === 'string' &&
    version !== PACKAGE_SCHEMA &&
    version.startsWith('aio.package/')
  ) {
    return err(`Package was written by a newer Stratlas (${version}). Update the app to open it.`);
  }
  const r = PackageHeader.safeParse(json);
  if (r.success) return ok(r.data);
  const first = r.error.issues[0];
  const where = first?.path.length ? ` at ${first.path.join('.')}` : '';
  return err(`Package header is invalid${where}: ${first?.message ?? 'unknown error'}`);
}
const BY_EXTENSION = {
  csv: 'issues-csv',
  pdf: 'report-pdf',
  geojson: 'issues-geojson',
  png: 'snapshot',
  jpg: 'snapshot',
  jpeg: 'snapshot',
  webp: 'snapshot',
  json: 'kit-json',
  zip: 'masks',
};
export function exportKindForFile(name) {
  const dot = name.lastIndexOf('.');
  const ext = dot < 0 ? '' : name.slice(dot + 1).toLowerCase();
  return BY_EXTENSION[ext] ?? 'files';
}
export function exportAllowed(allowed, name) {
  return allowed.includes(exportKindForFile(name));
}
