// Generated by tools/compat/extract-schema.mjs from packages/schema/src/procmodel.ts at 7faf945 (Stratlas 0.8). Do not edit.
import { z } from 'zod';
import { Id, IsoTime, Vec2, Vec3 } from './common.mjs';
export const PROCMODEL_SCHEMA = 'aio.procmodel/1';
export const PROCMODEL_DIR = 'models';
export const ProcModelId = z
  .string()
  .regex(/^[A-Za-z0-9][A-Za-z0-9_-]{0,80}$/, 'A model id is a plain file name.');
export const PartStatus = z.enum(['draft', 'accepted', 'rejected']);
export const ProcPartKind = z.enum(['extrusion', 'cylinder', 'box', 'pipe', 'sphere']);
export const PartOrigin = z.discriminatedUnion('by', [
  z
    .object({
      by: z.literal('fit'),
      residualM: z.number().nonnegative(),
      inliers: z.number().int().nonnegative(),
      inlierShare: z.number().min(0).max(1).optional(),
      runId: z.string().optional(),
    })
    .strict(),
  z
    .object({
      by: z.literal('drawing'),
      file: z.string().optional(),
      layer: z.string().optional(),
      entity: z.string().optional(),
    })
    .strict(),
  z
    .object({
      by: z.literal('agent'),
      runId: z.string().optional(),
      model: z.string().optional(),
    })
    .strict(),
  z
    .object({
      by: z.literal('manual'),
      author: z.string().optional(),
    })
    .strict(),
]);
const Positive = z.number().positive();
const partBase = {
  id: z.string().min(1).max(128),
  name: z.string().max(200).optional(),
  tag: z.string().max(80).optional(),
  class: z.string().max(40).optional(),
  status: PartStatus,
  confidence: z.number().min(0).max(1).optional(),
  origin: PartOrigin,
};
export const ProcPart = z.discriminatedUnion('kind', [
  z
    .object({
      kind: z.literal('extrusion'),
      ...partBase,
      footprint: z.array(Vec2).min(3),
      baseY: z.number(),
      height: Positive,
    })
    .strict(),
  z
    .object({
      kind: z.literal('cylinder'),
      ...partBase,
      base: Vec3,
      radius: Positive,
      height: Positive,
      roof: z.enum(['flat', 'cone', 'dome']).optional(),
      roofHeight: z.number().nonnegative().optional(),
    })
    .strict(),
  z
    .object({
      kind: z.literal('box'),
      ...partBase,
      base: Vec3,
      size: z.tuple([Positive, Positive, Positive]),
      yawDeg: z.number().min(-180).max(180).optional(),
    })
    .strict(),
  z
    .object({
      kind: z.literal('pipe'),
      ...partBase,
      points: z.array(Vec3).min(2),
      diameter: Positive,
    })
    .strict(),
  z
    .object({
      kind: z.literal('sphere'),
      ...partBase,
      center: Vec3,
      radius: Positive,
    })
    .strict(),
]);
export const ProcModel = z
  .object({
    schema: z.literal(PROCMODEL_SCHEMA),
    id: ProcModelId,
    name: z.string().min(1).max(200),
    createdAt: IsoTime,
    updatedAt: IsoTime,
    capture: Id.optional(),
    sources: z
      .array(
        z
          .object({
            kind: z.enum(['drawing', 'pointcloud', 'plan']),
            ref: z.string().min(1),
          })
          .strict(),
      )
      .optional(),
    parts: z.array(ProcPart),
  })
  .superRefine((m, ctx) => {
    const seen = new Set();
    m.parts.forEach((p, i) => {
      if (seen.has(p.id))
        ctx.addIssue({
          code: 'custom',
          message: `Duplicate part id "${p.id}"`,
          path: ['parts', i, 'id'],
        });
      seen.add(p.id);
    });
  });
export const ProcModelSummary = z.object({
  id: ProcModelId,
  name: z.string(),
  parts: z.number().int().nonnegative(),
  accepted: z.number().int().nonnegative(),
  updatedAt: z.string(),
  layer: Id.optional(),
});
