// Generated by tools/compat/extract-schema.mjs from packages/schema/src/update.ts at 7faf945 (Stratlas 0.8). Do not edit.
import { z } from 'zod';
export const UPDATE_FEED_SCHEMA = 'aio.update-feed/1';
export const UPDATE_FEED_FILE = 'stratlas-update.json';
export const UpdatePlatform = z.enum(['win-x64', 'win-arm64', 'mac-arm64', 'mac-x64']);
const Version = z.string().regex(/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/, 'a version like 1.2.3');
export const UpdateFile = z.object({
  url: z.string().min(1),
  sha256: z.string().regex(/^[0-9a-fA-F]{64}$/, '64 hex characters'),
  size: z.number().int().positive(),
});
export const UpdateFeed = z.object({
  schema: z.literal(UPDATE_FEED_SCHEMA),
  version: Version,
  releasedAt: z.string().optional(),
  notes: z.string().max(200_000).optional(),
  files: z.partialRecord(UpdatePlatform, UpdateFile),
});
export const ReleaseNotes = z.object({
  version: z.string(),
  markdown: z.string(),
});
export const UpdateStatus = z.object({
  current: z.string(),
  previous: z
    .object({
      version: z.string(),
      dir: z.string(),
    })
    .optional(),
  pending: z
    .object({
      from: z.string(),
      to: z.string(),
      failures: z.number().int().nonnegative(),
    })
    .optional(),
  rolledBack: z
    .object({
      from: z.string(),
      to: z.string(),
      at: z.string(),
    })
    .optional(),
  rollbackUnavailable: z.string().optional(),
});
