#!/usr/bin/env node
/* eslint-disable no-console -- command-line output */
// Extract `packages/schema/src` as it was at a milestone build into plain ES modules, so tests can
// parse files with the exact schemas an older Stratlas used. Types are stripped by Node's own
// stripper (`node:module`), relative imports gain `.mjs`, and the output is Prettier-formatted.
//
//   node tools/compat/extract-schema.mjs 0.8            -> tools/compat/schema-0.8/
//   node tools/compat/extract-schema.mjs 0.6 <out dir>  -> any folder (the corpus builder uses temp)
//
// Needs the git history (a full clone). CI runs from the committed `schema-0.8/` instead; the
// drift test re-extracts when the history is there.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { milestone } from './milestones.mjs';

export const repoRoot = fileURLToPath(new URL('../..', import.meta.url));
const SRC = 'packages/schema/src';

const git = (args) =>
  execFileSync('git', args, { cwd: repoRoot, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

/** Is `commit` in this clone (false in a shallow CI checkout)? */
export function hasCommit(commit) {
  try {
    git(['cat-file', '-e', `${commit}^{commit}`]);
    return true;
  } catch {
    return false;
  }
}

/** Schema sources (no tests, no fixtures) at `commit`: file name to TypeScript text. */
export function schemaSources(commit) {
  const names = git(['ls-tree', '--name-only', `${commit}`, `${SRC}/`])
    .split('\n')
    .map((p) => p.trim().split('/').pop() ?? '')
    .filter((n) => n.endsWith('.ts') && !n.endsWith('.test.ts'));
  return new Map(names.map((n) => [n, git(['show', `${commit}:${SRC}/${n}`])]));
}

/** TypeScript module text to an ES module with `.mjs` relative imports. */
export function toModule(ts) {
  const js = stripTypeScriptTypes(ts, { mode: 'transform' });
  return js.replace(/(from\s+['"])(\.{1,2}\/[^'"]+?)(['"])/g, (_, a, p, b) =>
    /\.[cm]?js$/.test(p) ? `${a}${p}${b}` : `${a}${p}.mjs${b}`,
  );
}

/** The schema sources of the working tree (the current build). */
export function workingTreeSources() {
  const dir = join(repoRoot, SRC);
  const names = readdirSync(dir).filter((n) => n.endsWith('.ts') && !n.endsWith('.test.ts'));
  return new Map(names.map((n) => [n, readFileSync(join(dir, n), 'utf8')]));
}

/** Write `sources` (file name to TypeScript) into `outDir` as Prettier-formatted `.mjs` modules. */
export async function writeModules(sources, outDir, origin) {
  const prettier = (await resolveConfig(join(repoRoot, 'x.mjs'))) ?? {};
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  for (const [name, ts] of sources) {
    const head = `// Generated by tools/compat/extract-schema.mjs from ${SRC}/${name} at ${origin}. Do not edit.\n`;
    const text = await format(head + toModule(ts), { ...prettier, parser: 'babel' });
    writeFileSync(join(outDir, name.replace(/\.ts$/, '.mjs')), text);
  }
  return readdirSync(outDir).sort();
}

/** Write the schema of milestone `version` into `outDir` as `.mjs` modules. */
export async function extractSchema(version, outDir) {
  const { commit } = milestone(version);
  return writeModules(schemaSources(commit), outDir, `${commit} (Stratlas ${version})`);
}

/**
 * A scratch folder inside the repository, so extracted modules resolve `zod` from the root
 * `node_modules` (a system temp folder would not).
 */
export function scratchDir(name) {
  return join(repoRoot, 'node_modules', '.cache', 'quadrion-compat', name);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const version = process.argv[2] ?? '0.8';
  const out = process.argv[3] ?? join(repoRoot, 'tools', 'compat', `schema-${version}`);
  const files = await extractSchema(version, out);
  console.log(`Extracted the ${version} schema (${String(files.length)} modules) into ${out}`);
}
