// Generated by tools/compat/extract-schema.mjs from packages/schema/src/blobs.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Id, Sha256Hex } from './common.mjs';
export const BlobRef = z.object({
  sha256: Sha256Hex,
  size: z.number().int().nonnegative(),
  path: z.string().min(1).max(1024),
  role: z.enum(['source', 'derived']),
  layer: Id.optional(),
});
export const BlobAddPayload = BlobRef;
export const BlobState = z.enum(['present', 'missing', 'partial', 'stale', 'streaming']);
export const FetchPolicy = z.enum(['always', 'on-open', 'on-demand', 'stream']);
export const LARGE_BLOB_BYTES = 200 * 1024 * 1024;
export const BLOB_PART_BYTES = 8 * 1024 * 1024;
export const MISSING_BLOB_HEADER = 'x-aio-blob';
export function missingBlobHeader(sha256, size) {
  return `missing ${sha256} ${size}`;
}
export function parseMissingBlobHeader(value) {
  const m = /^missing ([a-f0-9]{64}) (\d+)$/.exec(value.trim());
  return m?.[1] && m[2]
    ? {
        sha256: m[1],
        size: Number(m[2]),
      }
    : null;
}
export function blobPath(sha256) {
  return `blobs/${sha256.slice(0, 2)}/${sha256}`;
}
export const LayerBlobStatus = z.object({
  layer: Id,
  state: BlobState,
  policy: FetchPolicy,
  files: z.number().int().nonnegative(),
  bytes: z.number().int().nonnegative(),
  have: z.number().int().nonnegative(),
});
