// Generated by tools/compat/extract-schema.mjs from packages/schema/src/change.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Id, IsoTime, Vec3 } from './common.mjs';
export const CHANGE_SCHEMA = 'aio.change/1';
export const CHANGE_DIR = 'change';
export const ChangeSetId = z
  .string()
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,120}$/, 'A change set id is a plain file name.');
export const ChangeKind = z.enum(['issue', 'detection', 'vector', 'region', 'component', 'frame']);
export const ChangeVerdict = z.enum([
  'new',
  'resolved',
  'not-seen',
  'grown',
  'shrunk',
  'worsened',
  'improved',
  'added',
  'removed',
  'moved',
  'reshaped',
  'attributes',
  'changed',
  'cut',
  'fill',
  'unchanged',
]);
export const CHANGE_VERDICTS = {
  issue: ['new', 'resolved', 'not-seen', 'grown', 'shrunk', 'worsened', 'improved', 'unchanged'],
  detection: ['new', 'resolved', 'not-seen', 'grown', 'shrunk', 'unchanged'],
  vector: ['added', 'removed', 'moved', 'reshaped', 'attributes', 'unchanged'],
  region: ['added', 'removed', 'changed', 'cut', 'fill'],
  component: ['added', 'removed', 'moved', 'changed', 'unchanged'],
  frame: ['changed', 'unchanged'],
};
export const ChangeReview = z
  .object({
    status: z.enum(['open', 'confirmed', 'dismissed']),
    by: z.string().min(1),
    at: IsoTime,
    note: z.string().max(4000).optional(),
    issueId: Id.optional(),
  })
  .strict();
const LonLat = z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]);
export const LonLatRing = z.array(LonLat).min(3);
const FromTo = z
  .object({
    from: z.number().optional(),
    to: z.number().optional(),
  })
  .strict();
const itemBase = {
  id: z.string().min(1).max(200),
  label: z.string().max(300).optional(),
  score: z.number().min(0).max(1).optional(),
  at: Vec3.optional(),
  bounds: z
    .object({
      min: Vec3,
      max: Vec3,
    })
    .strict()
    .optional(),
  method: z.string().max(40).optional(),
  review: ChangeReview.optional(),
};
const IssueChange = z
  .object({
    kind: z.literal('issue'),
    ...itemBase,
    verdict: z.enum(CHANGE_VERDICTS.issue),
    from: Id.optional(),
    to: Id.optional(),
    classId: Id.optional(),
    size: FromTo.extend({
      unit: z.enum(['m', 'm2']),
    })
      .strict()
      .optional(),
    severity: FromTo.optional(),
  })
  .strict();
const DetectionChange = z
  .object({
    kind: z.literal('detection'),
    ...itemBase,
    verdict: z.enum(CHANGE_VERDICTS.detection),
    classId: z.string().min(1),
    zone: z.string().optional(),
    count: FromTo.optional(),
    fromIds: z.array(z.string()).optional(),
    toIds: z.array(z.string()).optional(),
  })
  .strict();
const VectorChange = z
  .object({
    kind: z.literal('vector'),
    ...itemBase,
    verdict: z.enum(CHANGE_VERDICTS.vector),
    layerFrom: Id.optional(),
    layerTo: Id.optional(),
    featureFrom: z.union([z.string(), z.number()]).optional(),
    featureTo: z.union([z.string(), z.number()]).optional(),
    distanceM: z.number().nonnegative().optional(),
    keys: z.array(z.string()).optional(),
  })
  .strict();
const RegionChange = z
  .object({
    kind: z.literal('region'),
    ...itemBase,
    verdict: z.enum(CHANGE_VERDICTS.region),
    outline: LonLatRing.optional(),
    outlineLocal: z.array(Vec3).min(3).optional(),
    areaM2: z.number().nonnegative().optional(),
    volume: z
      .object({
        cutM3: z.number().nonnegative(),
        fillM3: z.number().nonnegative(),
        netM3: z.number(),
      })
      .strict()
      .optional(),
    distance: z
      .object({
        meanM: z.number(),
        maxM: z.number(),
      })
      .strict()
      .optional(),
    layer: Id.optional(),
    feature: z.union([z.string(), z.number()]).optional(),
  })
  .strict();
const ComponentChange = z
  .object({
    kind: z.literal('component'),
    ...itemBase,
    verdict: z.enum(CHANGE_VERDICTS.component),
    part: z.string().min(1),
    nodeFrom: z.string().optional(),
    nodeTo: z.string().optional(),
    layerFrom: Id.optional(),
    layerTo: Id.optional(),
    offsetM: Vec3.optional(),
    deviation: z
      .object({
        meanM: z.number(),
        maxM: z.number(),
      })
      .strict()
      .optional(),
  })
  .strict();
export const FrameRef = z
  .object({
    layer: Id,
    t: z.number().nonnegative().optional(),
    photo: Id.optional(),
  })
  .strict()
  .refine((f) => (f.t === undefined) !== (f.photo === undefined), {
    message: 'A frame names a time or a photo, not both.',
  });
const FrameChange = z
  .object({
    kind: z.literal('frame'),
    ...itemBase,
    verdict: z.enum(CHANGE_VERDICTS.frame),
    a: FrameRef,
    b: FrameRef,
    poseM: z.number().nonnegative().optional(),
    angleDeg: z.number().nonnegative().optional(),
    detections: z.array(z.string()).optional(),
  })
  .strict();
export const ChangeItem = z.discriminatedUnion('kind', [
  IssueChange,
  DetectionChange,
  VectorChange,
  RegionChange,
  ComponentChange,
  FrameChange,
]);
export const ChangeRegistration = z
  .object({
    ok: z.boolean(),
    shiftPx: z.number().nonnegative().optional(),
    shiftM: z.number().nonnegative().optional(),
    tolerancePx: z.number().nonnegative().optional(),
    toleranceM: z.number().nonnegative().optional(),
    message: z.string().optional(),
  })
  .strict();
export const ChangeSet = z
  .object({
    schema: z.literal(CHANGE_SCHEMA),
    id: ChangeSetId,
    from: Id,
    to: Id,
    producer: z.string().min(1).max(64),
    run: z
      .object({
        jobId: z.string().optional(),
        at: IsoTime.optional(),
        params: z.record(z.string(), z.unknown()).optional(),
      })
      .strict()
      .optional(),
    createdAt: IsoTime,
    items: z.array(ChangeItem),
    layers: z.array(Id).default([]),
    stats: z.record(z.string(), z.number()).default({}),
    registration: ChangeRegistration.optional(),
    coverage: z.number().min(0).max(1).optional(),
  })
  .superRefine((s, ctx) => {
    if (s.from === s.to)
      ctx.addIssue({
        code: 'custom',
        message: 'A change set compares two dates.',
        path: ['to'],
      });
    const seen = new Set();
    s.items.forEach((item, i) => {
      if (seen.has(item.id))
        ctx.addIssue({
          code: 'custom',
          message: `Duplicate item id "${item.id}"`,
          path: ['items', i, 'id'],
        });
      seen.add(item.id);
    });
  });
export const ChangeSetSummary = z.object({
  id: ChangeSetId,
  from: Id,
  to: Id,
  producer: z.string(),
  createdAt: z.string(),
  items: z.number().int().nonnegative(),
  open: z.number().int().nonnegative(),
});
export const ChangeThresholds = z
  .object({
    cloud: z
      .object({
        significantM: z.number().positive().max(10).default(0.05),
        farM: z.number().positive().max(100).default(0.3),
      })
      .strict()
      .prefault({}),
    surface: z
      .object({
        minDepthM: z.number().positive().max(100).default(0.1),
        minAreaM2: z.number().positive().max(1e6).default(1),
      })
      .strict()
      .prefault({}),
    raster: z
      .object({
        preset: z.enum(['conservative', 'balanced', 'sensitive']).default('conservative'),
      })
      .strict()
      .prefault({}),
    grown: z
      .object({
        areaPct: z.number().positive().max(1000).default(20),
        severityLevels: z.number().int().min(1).max(10).default(1),
      })
      .strict()
      .prefault({}),
    registration: z
      .object({
        maxShiftPx: z.number().nonnegative().max(100).default(2),
        maxShiftM: z.number().nonnegative().max(10).default(0.05),
      })
      .strict()
      .prefault({}),
  })
  .strict();
export const DEFAULT_CHANGE_THRESHOLDS = ChangeThresholds.parse({});
