// Generated by tools/compat/extract-schema.mjs from packages/schema/src/common.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
export const Id = z.string().min(1).max(128);
export const Vec2 = z.tuple([z.number(), z.number()]);
export const Vec3 = z.tuple([z.number(), z.number(), z.number()]);
export const Quat = z.tuple([z.number(), z.number(), z.number(), z.number()]);
export const Mat4 = z.array(z.number()).length(16);
export const IsoTime = z.iso.datetime({
  offset: true,
});
export const IsoDate = z.iso.date();
export const HexColor = z.string().regex(/^#[0-9a-fA-F]{6}$/, 'Colour must be #rrggbb');
export const AssetRef = z.union([
  z
    .object({
      hash: z.string().regex(/^[a-f0-9]{64}$/),
    })
    .strict(),
  z
    .object({
      path: z.string().min(1),
    })
    .strict(),
]);
export const ProjectPath = z
  .string()
  .min(1)
  .max(260)
  .refine(
    (p) => {
      const n = p.replace(/\\/g, '/');
      return !n.startsWith('/') && !/^[A-Za-z]:/.test(n) && !n.split('/').includes('..');
    },
    {
      message: 'Output paths must stay inside the project folder.',
    },
  );
export const Sha256Hex = z
  .string()
  .regex(/^[a-f0-9]{64}$/, 'A SHA-256 is 64 lower-case hex digits.');
export const BASE32_ALPHABET = 'abcdefghijklmnopqrstuvwxyz234567';
export const Base64Url = z.string().regex(/^[A-Za-z0-9_-]+$/, 'Expected unpadded base64url.');
export const PublicKeyB64 = z
  .string()
  .regex(/^[A-Za-z0-9_-]{43}$/, 'An Ed25519 key is 43 base64url characters.');
export const SignatureB64 = z
  .string()
  .regex(/^[A-Za-z0-9_-]{86}$/, 'An Ed25519 signature is 86 base64url characters.');
export const Hlc = z
  .string()
  .regex(/^\d{13}\.\d{4}\.d_[a-z2-7]{52}$/, 'A clock reading is <ms>.<counter>.<device>.');
export const ok = (value) => ({
  ok: true,
  value,
});
export const err = (error) => ({
  ok: false,
  error,
});
export function uniqueIds(key) {
  return (value, ctx) => {
    const seen = new Set();
    for (const item of value[key]) {
      if (seen.has(item.id)) {
        ctx.addIssue({
          code: 'custom',
          message: `Duplicate id "${item.id}" in ${key}`,
          path: [key],
        });
      }
      seen.add(item.id);
    }
  };
}
