// Generated by tools/compat/extract-schema.mjs from packages/schema/src/detections.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Box, Point2, Polygon, RotBox } from './annotation.mjs';
import { Id, IsoTime } from './common.mjs';
export const DETECTIONS_SCHEMA = 'aio.detections/1';
export const DetectionSource = z.enum(['human', 'ai', 'model', 'import']);
export const DetectionStatus = z.enum(['accepted', 'draft', 'rejected']);
export const DetectionSpace = z.enum(['preview', 'source', 'normalized', 'sheet']);
export const DetectionBox = z
  .tuple([z.number(), z.number(), z.number(), z.number()])
  .refine((b) => b[2] > b[0] && b[3] > b[1], {
    message: 'A box needs x1 > x0 and y1 > y0.',
  });
export const DetectionFrame = z
  .object({
    layer: Id,
    t: z.number().nonnegative(),
  })
  .strict();
export const DetectionGeom = z.discriminatedUnion('type', [Box, RotBox, Polygon, Point2]);
export const DetectionOrigin = z
  .object({
    author: z.string().optional(),
    provider: z.string().optional(),
    model: z.string().optional(),
    promptVersion: z.string().optional(),
    runId: z.string().optional(),
  })
  .strict();
export const Detection = z
  .object({
    id: z.string().min(1).max(128).optional(),
    photo: Id.optional(),
    class: z.string().min(1),
    severity: z.union([z.number().int(), z.literal('uncertain')]).optional(),
    confidence: z.number().min(0).max(1).optional(),
    note: z.string().optional(),
    component: z.string().optional(),
    status: DetectionStatus.optional(),
    source: DetectionSource.optional(),
    bbox: DetectionBox,
    space: DetectionSpace.optional(),
    width: z.number().positive().optional(),
    height: z.number().positive().optional(),
    sheet: z.string().min(1).optional(),
    frame: DetectionFrame.optional(),
    geom: DetectionGeom.optional(),
    label: z.string().optional(),
    uncertain: z.boolean().optional(),
    origin: DetectionOrigin.optional(),
    issueId: Id.optional(),
    reviewedBy: z.string().optional(),
    reviewedAt: IsoTime.optional(),
    createdAt: IsoTime.optional(),
    updatedAt: IsoTime.optional(),
  })
  .superRefine((d, ctx) => {
    const space = d.space ?? 'preview';
    if (space === 'sheet' && !d.sheet)
      ctx.addIssue({
        code: 'custom',
        message: 'A sheet box names its sheet.',
        path: ['sheet'],
      });
    if (space !== 'sheet' && !d.photo && !d.frame)
      ctx.addIssue({
        code: 'custom',
        message: 'A detection names its photo or video frame.',
        path: ['photo'],
      });
    if (d.photo && d.frame)
      ctx.addIssue({
        code: 'custom',
        message: 'A detection is on a photo or a video frame, not both.',
        path: ['frame'],
      });
    if (d.frame && space !== 'source' && space !== 'normalized')
      ctx.addIssue({
        code: 'custom',
        message: 'A video frame box is in source pixels (with width and height) or normalized.',
        path: ['space'],
      });
    if (d.frame && space === 'source' && (!d.width || !d.height))
      ctx.addIssue({
        code: 'custom',
        message: 'A video frame box gives the width and height of the frame.',
        path: ['width'],
      });
    if (space === 'normalized' && d.bbox.some((v) => v < 0 || v > 1))
      ctx.addIssue({
        code: 'custom',
        message: 'Normalized boxes are 0 to 1.',
        path: ['bbox'],
      });
  });
export const DetectionRun = z
  .object({
    id: z.string().min(1),
    at: IsoTime.optional(),
    provider: z.string().optional(),
    model: z.string().optional(),
    promptVersion: z.string().optional(),
    images: z.number().int().nonnegative().optional(),
    detections: z.number().int().nonnegative().optional(),
    inputTokens: z.number().nonnegative().optional(),
    outputTokens: z.number().nonnegative().optional(),
    costUsd: z.number().nonnegative().optional(),
  })
  .strict();
export const DetectionsFile = z.object({
  schema: z.literal(DETECTIONS_SCHEMA),
  source: DetectionSource,
  producer: z.string().optional(),
  createdAt: IsoTime.optional(),
  layer: Id.optional(),
  assessed: z.union([z.literal('all'), z.array(Id)]).optional(),
  run: DetectionRun.optional(),
  detections: z.array(Detection),
});
