// Generated by tools/compat/extract-schema.mjs from packages/schema/src/entitlements.ts at e422fd3 (Stratlas 0.10). Do not edit.
export const ENTITLEMENTS = [
  'journal.history',
  'audit.export',
  'audit.verify',
  'exchange.files',
  'team.share',
  'team.sync',
  'team.hub',
  'team.server',
  'team.pull',
  'collab.comment',
  'collab.assign',
  'collab.approve',
];
export const ALWAYS_ALLOWED = ['journal.history', 'audit.export', 'audit.verify', 'team.pull'];
export const allowAll = {
  can: () => true,
};
let provider = allowAll;
export function setEntitlementProvider(next) {
  provider = next;
}
export function can(entitlement) {
  return ALWAYS_ALLOWED.includes(entitlement) || provider.can(entitlement);
}
