// Generated by tools/compat/extract-schema.mjs from packages/schema/src/globe.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { LonLatRing } from './change.mjs';
import { Id, IsoDate, IsoTime } from './common.mjs';
import { TilesetId, TilesetKind } from './tilesets.mjs';
export const RasterPackId = z
  .string()
  .regex(/^[a-z0-9-]+$/, 'A pack id is lower-case letters, digits and dashes.')
  .min(1)
  .max(48);
export const RasterPackKind = z.enum(['imagery', 'terrain']);
export const RASTER_PACK_DIRS = {
  imagery: 'packs/imagery',
  terrain: 'packs/terrain',
};
export const TerrainDatum = z.enum(['egm2008', 'egm96', 'ellipsoid']);
const rasterPackFields = {
  id: RasterPackId,
  kind: RasterPackKind,
  label: z.string().min(1).max(120),
  bbox: z.tuple([z.number(), z.number(), z.number(), z.number()]),
  minZoom: z.number().int().min(0).max(24),
  maxZoom: z.number().int().min(0).max(24),
  tileSize: z.union([z.literal(256), z.literal(512)]),
  format: z.enum(['webp', 'png', 'jpeg']),
  encoding: z.literal('terrarium').optional(),
  verticalDatum: TerrainDatum.optional(),
  licence: z.string().min(1).max(200),
  attribution: z.string().min(1).max(500),
  provenance: z.string().max(300).optional(),
  customerLicence: z.boolean(),
  builtAt: IsoTime,
};
const terrainRules = (p, ctx) => {
  if (p.kind === 'terrain' && (p.encoding === undefined || p.verticalDatum === undefined))
    ctx.addIssue({
      code: 'custom',
      message: 'A terrain pack names its encoding and vertical datum.',
      path: ['encoding'],
    });
  if (p.kind === 'imagery' && (p.encoding !== undefined || p.verticalDatum !== undefined))
    ctx.addIssue({
      code: 'custom',
      message: 'An imagery pack has no height encoding or vertical datum.',
      path: ['encoding'],
    });
};
export const RasterPackMeta = z
  .looseObject({
    schema: z.literal('aio.raster-pack/1'),
    ...rasterPackFields,
  })
  .superRefine(terrainRules);
export const RasterPackInfo = z
  .object({
    ...rasterPackFields,
    sizeBytes: z.number().int().nonnegative(),
    source: z.enum(['download', 'import', 'build-tool', 'package']).optional(),
  })
  .superRefine(terrainRules);
export const ImageryImportRequest = z
  .object({
    path: z.string().min(1).max(1024),
    id: RasterPackId.optional(),
    label: z.string().min(1).max(120),
    licence: z.string().min(1).max(200),
    attribution: z.string().min(1).max(500),
    provenance: z.string().max(300).optional(),
    customerLicence: z.boolean(),
  })
  .strict();
export const TerrainImportRequest = z
  .object({
    path: z.string().min(1).max(1024),
    id: RasterPackId.optional(),
    label: z.string().min(1).max(120),
    licence: z.string().min(1).max(200),
    attribution: z.string().min(1).max(500),
    provenance: z.string().max(300).optional(),
    verticalDatum: TerrainDatum,
    customerLicence: z.boolean().optional(),
  })
  .strict();
export const GlobeSite = z.object({
  projectId: z.string().min(1),
  name: z.string().min(1),
  lonLat: z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]),
  footprint: LonLatRing.optional(),
  captures: z.array(
    z.object({
      id: Id,
      label: z.string(),
      date: IsoDate,
    }),
  ),
  issues: z.object({
    open: z.number().int().nonnegative(),
    bySeverity: z.record(z.string(), z.number().int().nonnegative()),
  }),
  tilesets: z.array(
    z.object({
      id: TilesetId,
      name: z.string(),
      kind: TilesetKind,
    }),
  ),
});
export const GlobeSettings = z.looseObject({
  schema: z.literal('aio.globe-settings/1'),
  imagery: z.union([z.literal('auto'), RasterPackId]).optional(),
  terrain: z.union([z.literal('auto'), z.literal('off'), RasterPackId]).optional(),
  terrainExaggeration: z.number().min(1).max(5).optional(),
  showIssues: z.boolean().optional(),
  aroundSite: z
    .object({
      terrain: z.boolean(),
      imagery: z.boolean(),
    })
    .optional(),
});
export const defaultGlobeSettings = () => ({
  schema: 'aio.globe-settings/1',
  imagery: 'auto',
  terrain: 'auto',
  terrainExaggeration: 1,
  showIssues: true,
});
