// Generated by tools/compat/extract-schema.mjs from packages/schema/src/inference.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Id } from './common.mjs';
export const DETECTOR_SCHEMA = 'aio.detector/1';
export const DetectorLayout = z.enum(['yolo-v8', 'yolo-v5', 'detr', 'ssd', 'generic']);
export const DetectorModelId = z
  .string()
  .regex(/^[a-z0-9][a-z0-9._-]{0,63}$/, 'A model id is lower case letters, digits, . _ and -.');
const Triple = z.tuple([z.number(), z.number(), z.number()]);
export const DetectorModelCard = z
  .object({
    schema: z.literal(DETECTOR_SCHEMA),
    name: z.string().min(1).max(120),
    version: z.string().min(1).max(40),
    layout: DetectorLayout,
    input: z
      .object({
        width: z.number().int().min(16).max(8192),
        height: z.number().int().min(16).max(8192),
        tensor: z.enum(['nchw', 'nhwc']).optional(),
        color: z.enum(['rgb', 'bgr']).optional(),
        scale: z.number().positive().optional(),
        mean: Triple.optional(),
        std: Triple.optional(),
      })
      .strict(),
    classes: z.array(z.string().min(1).max(80)).min(1).max(1000),
    licence: z
      .string()
      .min(2)
      .max(80)
      .regex(/^[A-Za-z0-9.+\-() ]+$/, 'The licence is an SPDX expression.'),
    source: z.string().min(1).max(500),
    sha256: z.string().regex(/^[a-f0-9]{64}$/),
    description: z.string().max(2000).optional(),
    author: z.string().max(200).optional(),
    minConfidence: z.number().min(0).max(1).optional(),
  })
  .strict();
export const InferenceRuntime = z.object({
  available: z.boolean(),
  provider: z.enum(['dml', 'coreml', 'cpu']).optional(),
  version: z.string().optional(),
  backends: z.array(z.string().min(1).max(40)).max(32).optional(),
  problem: z.string().optional(),
});
export const DetectorModelInfo = z.object({
  id: DetectorModelId,
  card: DetectorModelCard,
  where: z.enum(['user', 'pack']),
  sizeBytes: z.number().int().nonnegative(),
});
export const InferenceItem = z.union([
  z
    .object({
      layer: Id,
      photo: Id,
    })
    .strict(),
  z
    .object({
      layer: Id,
      t: z.number().nonnegative(),
    })
    .strict(),
]);
export const InferenceSettings = z
  .object({
    modelsDir: z.string().max(1024).optional(),
    provider: z.enum(['auto', 'cpu']).optional(),
    memoryCapMb: z.number().int().min(256).max(65536).optional(),
  })
  .strict();
