// Generated by tools/compat/extract-schema.mjs from packages/schema/src/jobs.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { FrameRef, LonLatRing } from './change.mjs';
import { Id, ProjectPath, Vec3 } from './common.mjs';
import { RasterPackId, TerrainDatum } from './globe.mjs';
import { Crs } from './manifest.mjs';
import { PhotoPreset, PhotoProduct, PhotoRunId, PhotoSource } from './photogrammetry.mjs';
import { ProcModelId, ProcPartKind } from './procmodel.mjs';
import { TilesetId } from './tilesets.mjs';
export const PIPELINE_PROTOCOL = 'aio.pipelines/1';
export const PipelineName = z.enum([
  'aik.cameras',
  'aik.project',
  'aik.records',
  'volumetric.process',
  'pointcloud.to_copc',
  'inspection.run',
  'road.build',
  'system.selftest',
  'volumetric.build',
  'change.raster',
  'change.surface',
  'change.cloud',
  'change.mesh',
  'change.frames',
  'drawing.import',
  'model.fit_cloud',
  'photo.align',
  'photo.georef',
  'photo.products',
  'opf.import',
  'opf.export',
  'tiles.mesh',
  'tiles.cloud',
  'packs.imagery',
  'packs.terrain',
]);
export const PIPELINES = [
  {
    name: 'aik.cameras',
    title: 'Cameras from photos',
    description: 'Camera poses from EXIF GPS and DJI gimbal angles, and 2560 px review copies.',
  },
  {
    name: 'aik.project',
    title: 'Place findings on the model',
    description: 'Back-projects finding boxes and masks onto the GLB as pins or textured patches.',
  },
  {
    name: 'aik.records',
    title: 'Findings register and stats',
    description: 'Findings with heights, zones and sides, the summary stats and the CSV.',
  },
  {
    name: 'volumetric.process',
    title: 'Stockpile volumes',
    description: 'Piles from DSM GeoTIFFs, four bases, volumes and change between two dates.',
  },
  {
    name: 'volumetric.build',
    title: 'Volumetric survey',
    description:
      'Raw DSM and ortho GeoTIFFs (or point clouds) per date to piles, toe lines, four bases, volumes, change and terrain.',
  },
  {
    name: 'pointcloud.to_copc',
    title: 'Point cloud to COPC',
    description: 'LAS, LAZ or E57 to a COPC file in the project CRS, added as a layer (PDAL).',
  },
  {
    name: 'inspection.run',
    title: 'Inspection: detections to issues',
    description:
      'Contact sheets, detections placed on the model, grouped into issues, and the stats for the report.',
  },
  {
    name: 'road.build',
    title: 'Road survey',
    description:
      'Ortho tiles, chainage from the centreline, defect polygons, ASTM D6433 sample units, deducts and PCI.',
  },
  {
    name: 'system.selftest',
    title: 'Check the pipeline pack',
    description:
      'Loads every library the pipelines need; optionally waits to try cancel and resume.',
  },
  {
    name: 'change.raster',
    title: 'Imagery change',
    description:
      'Two orthos of the same area: co-registration check, illumination-robust difference, change heat map and polygons.',
  },
  {
    name: 'change.surface',
    title: 'Surface change',
    description:
      'Two DSMs or point clouds: DEM of difference, cut and fill regions with volumes, and the site total.',
  },
  {
    name: 'change.cloud',
    title: 'Point cloud change',
    description:
      'Cloud-to-cloud distance as a COPC with a Distance field, and change regions from the points that moved.',
  },
  {
    name: 'change.mesh',
    title: '3D model change',
    description:
      'Deviation of the later model from the earlier one, and tagged parts added, removed, moved or changed.',
  },
  {
    name: 'change.frames',
    title: 'Change in matched frames',
    description:
      'Frame and photo pairs of two dates aligned by features; changes become draft detections.',
  },
  {
    name: 'drawing.import',
    title: 'Drawing import (DXF)',
    description:
      'A DXF plot plan in its units, placed by control points: vector layers per layer group, a plan raster and height hints.',
  },
  {
    name: 'model.fit_cloud',
    title: 'Model from point cloud',
    description:
      'Ground removal, clustering and primitive fitting (tanks, boxes, buildings, pipes) into draft model parts.',
  },
  {
    name: 'photo.align',
    title: 'Align photos',
    description:
      'Drone photos to calibrated cameras and a sparse model: EXIF and RTK tags, matching, structure from motion and GNSS georeferencing.',
  },
  {
    name: 'photo.georef',
    title: 'Adjust with ground control',
    description:
      'Bundle adjustment with marked control points; checkpoints measured only; the accuracy report.',
  },
  {
    name: 'photo.products',
    title: 'Create products from photos',
    description:
      'Dense cloud (COPC), DSM and DTM, orthomosaic and textured mesh from an aligned run, as new layers.',
  },
  {
    name: 'opf.import',
    title: 'OPF import',
    description:
      'An Open Photogrammetry Format project: calibrated cameras, control points and its outputs as layers.',
  },
  {
    name: 'opf.export',
    title: 'OPF export',
    description:
      'A processing run as an OPF project: cameras, calibration, control points, CRS and the sparse cloud.',
  },
  {
    name: 'tiles.mesh',
    title: 'Mesh to 3D Tiles',
    description:
      'A large mesh to a 3D Tiles 1.1 tileset placed through the project CRS, for the site view and the Globe.',
  },
  {
    name: 'tiles.cloud',
    title: 'Point cloud to 3D Tiles',
    description:
      'A COPC point cloud to a 3D Tiles points tileset following its hierarchy, for the Globe.',
  },
  {
    name: 'packs.imagery',
    title: 'Imagery pack',
    description:
      'GeoTIFF or COG imagery to an offline raster pack (PMTiles, WebP, Web Mercator) with its licence and attribution.',
  },
  {
    name: 'packs.terrain',
    title: 'Terrain pack',
    description:
      'A DEM to an offline terrain pack (Terrarium tiles in PMTiles) with its vertical datum, licence and attribution.',
  },
];
const Latitude = z.number().min(-90).max(90);
const Longitude = z.number().min(-180).max(180);
const KitConfig = z.record(z.string(), z.unknown());
export const AikCamerasParams = z
  .object({
    photos: z.string().min(1),
    origin: z.tuple([Latitude, Longitude, z.number()]).optional(),
    assetHeight: z.number().min(0.1).max(2000).optional(),
    sensorWidthMm: z.number().min(1).max(100).optional(),
    longEdge: z.number().int().min(256).max(16384).optional(),
    out: ProjectPath.optional(),
    photosOut: ProjectPath.optional(),
    altitude: z.enum(['auto', 'absolute', 'relative']).optional(),
    takeoffHeight: z.number().min(-500).max(5000).optional(),
  })
  .strict();
export const AikProjectParams = z
  .object({
    job: z.string().min(1).optional(),
    config: KitConfig.optional(),
    grid: z.number().int().min(4).max(256).optional(),
    placement: z.enum(['point', 'patch', 'none']).optional(),
    out: ProjectPath.optional(),
  })
  .strict();
export const AikRecordsParams = z
  .object({
    job: z.string().min(1).optional(),
    config: KitConfig.optional(),
    out: ProjectPath.optional(),
    csv: ProjectPath.optional(),
  })
  .strict();
export const VolumetricProcessParams = z
  .object({
    job: z.string().min(1).optional(),
    config: KitConfig.optional(),
    out: ProjectPath.optional(),
  })
  .strict();
export const VolumetricSurvey = z
  .object({
    id: z
      .string()
      .regex(/^[a-z0-9][a-z0-9-]{0,15}$/)
      .optional(),
    date: z.iso.date(),
    label: z.string().min(1).optional(),
    dsm: z.string().min(1).optional(),
    cloud: z.string().min(1).optional(),
    ortho: z.string().min(1).optional(),
  })
  .loose()
  .refine((s) => Boolean(s.dsm) !== Boolean(s.cloud), {
    message: 'Each survey needs a DSM or a point cloud.',
  });
export const VolumetricBuildConfig = z
  .object({
    epochs: z.array(VolumetricSurvey).min(1).max(2),
    grid: z.record(z.string(), z.number()).optional(),
    detect: z.record(z.string(), z.unknown()).optional(),
    volume: z.record(z.string(), z.unknown()).optional(),
  })
  .loose();
export const VolumetricBuildParams = z
  .object({
    job: z.string().min(1).optional(),
    config: VolumetricBuildConfig.optional(),
  })
  .strict();
export const PointcloudToCopcParams = z
  .object({
    src: z.string().min(1),
    out: ProjectPath.optional(),
    epsg: z.number().int().min(1024).max(999999).optional(),
    origin: z.tuple([z.number(), z.number(), z.number()]).optional(),
  })
  .strict();
export const InspectionRunParams = z
  .object({
    detections: z.union([z.string().min(1), z.array(z.string().min(1)).min(1)]).optional(),
    includeDrafts: z.boolean().optional(),
    minConfidence: z.number().min(0).max(1).optional(),
    clusterM: z.number().min(0.01).max(1000).optional(),
    hfovDeg: z.number().min(1).max(179).optional(),
    profile: z.enum(['stack', 'tank', 'telecom-tower', 'ohtl-tower']).optional(),
    sheetsPer: z.number().int().min(1).max(64).optional(),
    sheetWidth: z.number().int().min(400).max(8000).optional(),
    yoloNames: z.union([z.string().min(1), z.array(z.string().min(1)).min(1)]).optional(),
    out: ProjectPath.optional(),
  })
  .strict();
const Epsg = z.number().int().min(1024).max(999999);
export const RoadBuildParams = z
  .object({
    centreline: z.string().min(1),
    centrelineEpsg: Epsg.optional(),
    ortho: z.union([z.string().min(1), z.array(z.string().min(1)).min(1)]).optional(),
    orthoCm: z.number().min(0.5).max(100).optional(),
    defects: z.string().min(1).optional(),
    defectsEpsg: Epsg.optional(),
    pavement: z.string().min(1).optional(),
    units: z.enum(['chainage', 'grid']).optional(),
    unitLength: z.number().min(5).max(200).optional(),
    lanes: z.number().int().min(1).max(12).optional(),
    laneWidth: z.number().min(2).max(6).optional(),
    gridOrigin: z.tuple([z.number(), z.number()]).optional(),
    closeups: z.boolean().optional(),
    name: z.string().min(1).optional(),
  })
  .strict();
export const SelfTestParams = z
  .object({
    seconds: z.number().min(0).max(600).optional(),
  })
  .strict();
const CapturePair = z
  .object({
    from: Id,
    to: Id,
  })
  .strict();
const LocalBox = z
  .object({
    min: Vec3,
    max: Vec3,
  })
  .strict();
export const ChangeRasterParams = z
  .object({
    from: Id,
    to: Id,
    layerFrom: Id,
    layerTo: Id,
    method: z.enum(['gradient', 'ssim', 'rgb']),
    threshold: z.number().min(0).max(1).optional(),
    minAreaM2: z.number().positive().max(1e6).optional(),
    maxShiftPx: z.number().min(0).max(100).optional(),
    mask: LonLatRing.optional(),
    ignore: z.array(LonLatRing).max(200).optional(),
    out: ProjectPath.optional(),
  })
  .strict();
const SurfaceInput = z
  .object({
    layer: Id,
    kind: z.enum(['dsm', 'cloud']),
  })
  .strict();
export const ChangeSurfaceParams = z
  .object({
    from: SurfaceInput,
    to: SurfaceInput,
    captures: CapturePair.optional(),
    cellM: z.number().min(0.01).max(100).optional(),
    minDepthM: z.number().positive().max(100).optional(),
    minAreaM2: z.number().positive().max(1e6).optional(),
    areas: z
      .array(
        z
          .object({
            id: Id,
            name: z.string().min(1).max(120),
            ring: LonLatRing,
          })
          .strict(),
      )
      .max(500)
      .optional(),
    out: ProjectPath.optional(),
  })
  .strict();
export const ChangeCloudParams = z
  .object({
    layerFrom: Id,
    layerTo: Id,
    captures: CapturePair.optional(),
    minDistM: z.number().positive().max(10).optional(),
    maxDistM: z.number().positive().max(100).optional(),
    signed: z.boolean().optional(),
    spacingM: z.number().positive().max(10).optional(),
    region: LocalBox.optional(),
    out: ProjectPath.optional(),
  })
  .strict();
export const ChangeMeshParams = z
  .object({
    layerFrom: Id,
    layerTo: Id,
    captures: CapturePair.optional(),
    samples: z.number().int().min(1000).max(50_000_000).optional(),
    minDistM: z.number().positive().max(10).optional(),
    maxDistM: z.number().positive().max(100).optional(),
    out: ProjectPath.optional(),
  })
  .strict();
export const ChangeFramesParams = z
  .object({
    pairs: z
      .array(
        z
          .object({
            a: FrameRef,
            b: FrameRef,
          })
          .strict(),
      )
      .min(1)
      .max(5000)
      .optional(),
    from: Id.optional(),
    to: Id.optional(),
    maxPoseM: z.number().positive().max(1000).optional(),
    maxAngleDeg: z.number().positive().max(180).optional(),
    minAreaPx: z.number().int().min(1).optional(),
    out: ProjectPath.optional(),
  })
  .strict()
  .refine((p) => Boolean(p.pairs) || (Boolean(p.from) && Boolean(p.to)), {
    message: 'Give the frame pairs, or the two dates to pair.',
  });
export const DrawingControlPoint = z
  .object({
    drawing: z.tuple([z.number(), z.number()]),
    lonLat: z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]).optional(),
    local: Vec3.optional(),
  })
  .strict()
  .refine((c) => (c.lonLat === undefined) !== (c.local === undefined), {
    message: 'A control point is placed on the map (lonLat) or in the model (local).',
  });
export const DrawingImportParams = z
  .object({
    src: z.string().min(1),
    units: z.enum(['mm', 'cm', 'm', 'in', 'ft', 'us-ft']).optional(),
    layers: z.array(z.string().min(1)).max(1000).optional(),
    control: z.array(DrawingControlPoint).min(2).max(50).optional(),
    out: ProjectPath.optional(),
  })
  .strict();
export const ModelFitParams = z
  .object({
    layer: Id,
    region: z.union([LocalBox, LonLatRing]).optional(),
    kinds: z.array(ProcPartKind).min(1).optional(),
    distM: z.number().positive().max(5).optional(),
    minInliers: z.number().int().min(10).optional(),
    model: ProcModelId.optional(),
  })
  .strict();
const MAX_PATH = 1024;
export const PhotoAlignParams = z
  .object({
    photos: PhotoSource,
    run: PhotoRunId.optional(),
    preset: PhotoPreset,
    matching: z.enum(['auto', 'gps', 'sequential', 'exhaustive']).optional(),
    mapper: z.enum(['auto', 'global', 'incremental']).optional(),
    gnss: z.enum(['auto', 'rtk', 'standard', 'ignore']).optional(),
    ppk: z.string().min(1).max(MAX_PATH).optional(),
    crs: Crs.optional(),
    maxImageSize: z.number().int().min(320).max(20_000).optional(),
  })
  .strict();
export const PhotoGeorefParams = z
  .object({
    run: PhotoRunId,
    gcp: ProjectPath.optional(),
    useGnss: z.boolean().optional(),
  })
  .strict();
export const PhotoProductsParams = z
  .object({
    run: PhotoRunId,
    products: z.array(PhotoProduct).min(1),
    preset: PhotoPreset.optional(),
    dense: z.enum(['auto', 'cpu', 'cuda']).optional(),
    gsdCm: z.number().min(0.1).max(1000).optional(),
    region: LonLatRing.optional(),
    capture: Id.optional(),
    meshTriangles: z.number().int().min(10_000).max(50_000_000).optional(),
  })
  .strict();
export const OpfImportParams = z
  .object({
    src: z.string().min(1).max(MAX_PATH),
    products: z.array(z.enum(['cloud', 'ortho', 'dsm', 'mesh'])).optional(),
    photosRoot: z.string().min(1).max(MAX_PATH).optional(),
  })
  .strict();
export const OpfExportParams = z
  .object({
    run: PhotoRunId,
    out: z.string().min(1).max(MAX_PATH),
  })
  .strict();
export const TilesMeshParams = z
  .object({
    layer: Id.optional(),
    src: ProjectPath.optional(),
    id: TilesetId.optional(),
    name: z.string().min(1).max(200).optional(),
    run: PhotoRunId.optional(),
    compression: z.enum(['meshopt', 'draco', 'none']).optional(),
    maxTrianglesPerTile: z.number().int().min(1000).max(5_000_000).optional(),
    textureMaxPx: z.number().int().min(64).max(16_384).optional(),
  })
  .strict()
  .refine((p) => (p.layer === undefined) !== (p.src === undefined), {
    message: 'Give a mesh layer or a mesh file, not both.',
  });
export const TilesCloudParams = z
  .object({
    layer: Id,
    id: TilesetId.optional(),
    name: z.string().min(1).max(200).optional(),
    maxPointsPerTile: z.number().int().min(1000).max(5_000_000).optional(),
  })
  .strict();
const rasterPackParams = {
  src: z.array(z.string().min(1).max(MAX_PATH)).min(1).max(10_000),
  dest: z.string().min(1).max(MAX_PATH),
  id: RasterPackId,
  label: z.string().min(1).max(120),
  licence: z.string().min(1).max(200),
  attribution: z.string().min(1).max(500),
  provenance: z.string().max(300).optional(),
  minZoom: z.number().int().min(0).max(22).optional(),
  maxZoom: z.number().int().min(0).max(22).optional(),
};
export const ImageryPackParams = z
  .object({
    ...rasterPackParams,
    customerLicence: z.boolean(),
    format: z.enum(['webp', 'png', 'jpeg']).optional(),
    quality: z.number().int().min(1).max(100).optional(),
    tileSize: z.union([z.literal(256), z.literal(512)]).optional(),
  })
  .strict();
export const TerrainPackParams = z
  .object({
    ...rasterPackParams,
    verticalDatum: TerrainDatum,
    customerLicence: z.boolean().optional(),
    format: z.enum(['webp', 'png']).optional(),
  })
  .strict();
const PARAMS = {
  'aik.cameras': AikCamerasParams,
  'aik.project': AikProjectParams,
  'aik.records': AikRecordsParams,
  'volumetric.process': VolumetricProcessParams,
  'pointcloud.to_copc': PointcloudToCopcParams,
  'inspection.run': InspectionRunParams,
  'road.build': RoadBuildParams,
  'system.selftest': SelfTestParams,
  'volumetric.build': VolumetricBuildParams,
  'change.raster': ChangeRasterParams,
  'change.surface': ChangeSurfaceParams,
  'change.cloud': ChangeCloudParams,
  'change.mesh': ChangeMeshParams,
  'change.frames': ChangeFramesParams,
  'drawing.import': DrawingImportParams,
  'model.fit_cloud': ModelFitParams,
  'photo.align': PhotoAlignParams,
  'photo.georef': PhotoGeorefParams,
  'photo.products': PhotoProductsParams,
  'opf.import': OpfImportParams,
  'opf.export': OpfExportParams,
  'tiles.mesh': TilesMeshParams,
  'tiles.cloud': TilesCloudParams,
  'packs.imagery': ImageryPackParams,
  'packs.terrain': TerrainPackParams,
};
export function pipelineParams(name) {
  return PARAMS[name];
}
export const JobId = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/, 'Not a valid job id');
export function newJobId(pipeline, at, random = Math.random) {
  const p2 = (n) => String(n).padStart(2, '0');
  const stamp = `${String(at.getFullYear())}${p2(at.getMonth() + 1)}${p2(at.getDate())}-${p2(at.getHours())}${p2(at.getMinutes())}${p2(at.getSeconds())}`;
  const tail = Math.floor(random() * 36 ** 4)
    .toString(36)
    .padStart(4, '0');
  return `${stamp}-${pipeline.replace('.', '-')}-${tail}`;
}
export const JobStatus = z.enum([
  'starting',
  'running',
  'cancelling',
  'done',
  'failed',
  'cancelled',
  'interrupted',
]);
export const StepState = z.enum(['pending', 'running', 'done', 'skipped', 'failed', 'cancelled']);
export const JobStep = z.object({
  name: z.string(),
  title: z.string().optional(),
  state: StepState,
  message: z.string().optional(),
});
export const JobArtifact = z.object({
  path: z.string(),
  kind: z.string(),
});
export const JobRecord = z.object({
  id: JobId,
  pipeline: PipelineName,
  project: z.string().min(1),
  params: z.record(z.string(), z.unknown()),
  status: JobStatus,
  progress: z.number().min(0).max(1),
  steps: z.array(JobStep),
  message: z.string().optional(),
  error: z.string().optional(),
  artifacts: z.array(JobArtifact),
  createdAt: z.string(),
  updatedAt: z.string(),
  finishedAt: z.string().optional(),
  packVersion: z.string().optional(),
});
export const JobLogLine = z.object({
  time: z.string(),
  level: z.enum(['debug', 'info', 'warn', 'error', 'stderr']),
  message: z.string(),
  step: z.string().optional(),
});
export const RuntimeInfo = z.object({
  found: z.boolean(),
  version: z.string().optional(),
  dir: z.string().optional(),
  problem: z.string().optional(),
});
export const JobStartRequest = z.union([
  z
    .object({
      pipeline: PipelineName,
      project: z.string().min(1),
      params: z.record(z.string(), z.unknown()),
    })
    .strict(),
  z
    .object({
      resume: JobId,
    })
    .strict(),
]);
export const JobEvent = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('update'),
    job: JobRecord,
  }),
  z.object({
    type: z.literal('log'),
    jobId: JobId,
    line: JobLogLine,
  }),
]);
export const PipelinePackManifest = z.object({
  schema: z.literal('aio.pipeline-pack/1'),
  version: z.string().min(1),
  protocol: z.string(),
  python: z.object({
    version: z.string(),
    build: z.string(),
    executable: z.string().min(1),
  }),
  platform: z.string(),
  createdAt: z.string(),
  pipelines: z.array(
    z.object({
      name: z.string(),
      title: z.string(),
    }),
  ),
  appRange: z.string().min(1).max(100).optional(),
  files: z.record(
    z.string(),
    z.object({
      size: z.number().int().nonnegative(),
      sha256: z.string().regex(/^[a-f0-9]{64}$/),
    }),
  ),
});
