// Generated by tools/compat/extract-schema.mjs from packages/schema/src/journal.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { BlobAddPayload } from './blobs.mjs';
import {
  ApprovalPayload,
  ApprovalWithdrawPayload,
  AssignPayload,
  CommentDeletePayload,
  CommentEditPayload,
  CommentPayload,
  CommentRedactPayload,
  PolicySetPayload,
} from './collab.mjs';
import { Hlc, Id, IsoTime, Sha256Hex, SignatureB64 } from './common.mjs';
import {
  ActorId,
  DeviceId,
  DeviceRevokePayload,
  MemberAddPayload,
  MemberLinkPayload,
  MemberRemovePayload,
  MemberRolePayload,
} from './identity.mjs';
export const OP_SCHEMA = 'aio.op/1';
export const CHECKPOINT_SCHEMA = 'aio.checkpoint/1';
export const JOURNAL_DIR = 'journal';
export const JOURNAL_DEVICES_DIR = 'journal/devices';
export const JOURNAL_OPS_DIR = 'journal/ops';
export const JOURNAL_CHECKPOINTS_DIR = 'journal/checkpoints';
export const SEGMENT_MAX_BYTES = 4 * 1024 * 1024;
export const SEGMENT_MAX_OPS = 10_000;
export const CHECKPOINT_EVERY_OPS = 500;
export const CLOCK_AHEAD_NOTICE_MS = 5 * 60 * 1000;
export const CLOCK_AHEAD_HOLD_MS = 24 * 60 * 60 * 1000;
export const SIGNING_DOMAINS = {
  op: 'aio.op/1',
  checkpoint: 'aio.checkpoint/1',
  device: 'aio.device/1',
  cert: 'aio.cert/1',
  idcard: 'aio.idcard/1',
  exchange: 'aio.exchange/1',
  receipt: 'aio.receipt/1',
  request: 'aio.request/1',
};
export const OpId = Sha256Hex;
export const ReplicaId = z
  .string()
  .regex(/^r_[a-z2-7]{16}$/, 'A replica id is r_ and 16 base32 letters.');
export const ChainId = z
  .string()
  .regex(/^d_[a-z2-7]{52}\.r_[a-z2-7]{16}$/, 'A chain id is <device>.<replica>.');
export const Seq = z.number().int().min(1);
export const OP_KINDS = [
  'issue.create',
  'issue.patch',
  'issue.delete',
  'issue.restore',
  'issue.sighting.add',
  'issue.sighting.remove',
  'issue.status',
  'issue.merge',
  'issue.recode',
  'comment.add',
  'comment.edit',
  'comment.delete',
  'comment.redact',
  'assign.set',
  'approval.add',
  'approval.withdraw',
  'change.review',
  'detection.review',
  'procmodel.part',
  'manifest.entry',
  'boundary.edit',
  'narrative.version',
  'blob.add',
  'member.add',
  'member.role',
  'member.remove',
  'member.link',
  'device.revoke',
  'policy.set',
  'project.share',
  'package.export',
  'exchange.import',
  'conflict.resolve',
  'record.external',
  'checkpoint',
  'journal.off',
  'journal.on',
  'op.redact',
];
export const OpKind = z.enum(OP_KINDS);
export const OpKindName = z
  .string()
  .max(64)
  .regex(/^[a-z][a-z-]*(\.[a-z][a-z-]*)*$/, 'An op kind is dotted lower-case words.');
export const RECORD_KINDS = [
  'issue',
  'comment',
  'assignment',
  'approval',
  'change-item',
  'change-set',
  'detection',
  'detection-pass',
  'part',
  'model',
  'manifest',
  'boundary',
  'narrative',
  'report',
  'blob',
  'member',
  'device',
  'policy',
  'project',
  'op',
  'file',
];
export const RecordKind = z.enum(RECORD_KINDS);
export const RecordRef = z.looseObject({
  rec: z.string().min(1).max(40),
  id: z.string().min(1).max(300),
  in: z.string().min(1).max(300).optional(),
});
export const Via = z.union([
  z.looseObject({
    agent: z.looseObject({
      conversation: z.string().min(1).max(128),
      callId: z.string().min(1).max(128),
      provider: z.string().max(64).optional(),
      model: z.string().max(128).optional(),
    }),
  }),
  z.looseObject({
    pipeline: z.looseObject({
      name: z.string().min(1).max(64),
      jobId: z.string().min(1).max(128),
      packVersion: z.string().max(40).optional(),
    }),
  }),
  z.looseObject({
    import: z.looseObject({
      source: z.enum(['exchange', 'hub', 'server', 'reply', 'package']),
      ref: z.string().max(300).optional(),
      from: DeviceId.optional(),
    }),
  }),
  z.looseObject({
    external: z.looseObject({
      found: z.enum(['open', 'job', 'sync']),
      file: z.string().max(1024).optional(),
    }),
  }),
]);
export const Op = z
  .looseObject({
    v: z.literal(1),
    id: OpId,
    chain: ChainId,
    dev: DeviceId,
    act: ActorId,
    seq: Seq,
    hlc: Hlc,
    prev: OpId.nullable(),
    deps: z.record(ChainId, OpId).optional(),
    kind: OpKindName,
    target: RecordRef,
    base: Sha256Hex.optional(),
    ph: Sha256Hex,
    payload: z.unknown().optional(),
    via: Via.optional(),
    label: z.string().max(200).optional(),
    sig: SignatureB64.optional(),
  })
  .superRefine((op, ctx) => {
    if (!op.chain.startsWith(`${op.dev}.`)) {
      ctx.addIssue({
        code: 'custom',
        message: 'The chain does not belong to the device.',
        path: ['chain'],
      });
    }
    if (!op.hlc.endsWith(`.${op.dev}`)) {
      ctx.addIssue({
        code: 'custom',
        message: 'The clock reading is not from the device.',
        path: ['hlc'],
      });
    }
    if ((op.seq === 1) !== (op.prev === null)) {
      ctx.addIssue({
        code: 'custom',
        message: 'Only the first op of a chain has no prev.',
        path: ['prev'],
      });
    }
  });
export const OP_ID_EXCLUDES = ['id', 'payload', 'sig'];
export const PatchPayload = z.object({
  set: z.record(z.string(), z.unknown()).optional(),
  unset: z.array(z.string()).optional(),
  was: z.record(z.string(), z.unknown()).optional(),
});
export const RecordPayload = z.object({
  record: z.record(z.string(), z.unknown()),
});
export const IssueStatusPayload = z.object({
  from: z.string().min(1),
  to: z.string().min(1),
});
export const IssueMergePayload = z.object({
  into: Id,
});
export const IssueRecodePayload = z.object({
  from: z.string(),
  to: z.string(),
});
export const SightingPayload = z.object({
  hash: Sha256Hex,
  sighting: z.record(z.string(), z.unknown()).optional(),
});
export const ExternalPayload = z.object({
  file: z.string().min(1).max(1024),
  before: Sha256Hex.nullable(),
  after: Sha256Hex.nullable(),
  patch: PatchPayload.optional(),
});
export const RedactPayload = z.object({
  op: OpId,
  chain: ChainId,
  seq: Seq,
  reason: z.string().max(500).optional(),
});
export const ConflictResolvePayload = z.object({
  conflict: z.string().min(1).max(300),
  choice: z.enum(['ours', 'theirs', 'restore']),
  value: z.unknown().optional(),
});
export const CheckpointPayload = z.object({
  file: z.string().min(1),
  root: Sha256Hex,
  count: z.number().int(),
});
export const ProjectSharePayload = z.object({
  teamProjectId: z.string().min(1).max(64),
  name: z.string().min(1).max(200),
});
export const PackageExportPayload = z.object({
  file: z.string().min(1).max(260),
  readOnly: z.boolean(),
  history: z.enum(['none', 'summary', 'full']),
});
export const ExchangeImportPayload = z.object({
  exchange: z.string().min(1).max(64),
  kind: z.enum(['patch', 'bundle', 'reply']),
  ops: z.number().int().nonnegative(),
});
export const JournalSwitchPayload = z.object({
  reason: z.string().max(500).optional(),
});
export const OP_PAYLOADS = {
  'issue.create': RecordPayload,
  'issue.patch': PatchPayload,
  'issue.delete': z.object({}),
  'issue.restore': RecordPayload,
  'issue.sighting.add': SightingPayload,
  'issue.sighting.remove': SightingPayload,
  'issue.status': IssueStatusPayload,
  'issue.merge': IssueMergePayload,
  'issue.recode': IssueRecodePayload,
  'comment.add': CommentPayload,
  'comment.edit': CommentEditPayload,
  'comment.delete': CommentDeletePayload,
  'comment.redact': CommentRedactPayload,
  'assign.set': AssignPayload,
  'approval.add': ApprovalPayload,
  'approval.withdraw': ApprovalWithdrawPayload,
  'change.review': PatchPayload,
  'detection.review': PatchPayload,
  'procmodel.part': PatchPayload,
  'manifest.entry': PatchPayload,
  'boundary.edit': RecordPayload,
  'narrative.version': RecordPayload,
  'blob.add': BlobAddPayload,
  'member.add': MemberAddPayload,
  'member.role': MemberRolePayload,
  'member.remove': MemberRemovePayload,
  'member.link': MemberLinkPayload,
  'device.revoke': DeviceRevokePayload,
  'policy.set': PolicySetPayload,
  'project.share': ProjectSharePayload,
  'package.export': PackageExportPayload,
  'exchange.import': ExchangeImportPayload,
  'conflict.resolve': ConflictResolvePayload,
  'record.external': ExternalPayload,
  checkpoint: CheckpointPayload,
  'journal.off': JournalSwitchPayload,
  'journal.on': JournalSwitchPayload,
  'op.redact': RedactPayload,
};
export const OP_PERMISSION = {
  'issue.create': 'edit',
  'issue.patch': 'edit',
  'issue.delete': 'edit',
  'issue.restore': 'edit',
  'issue.sighting.add': 'edit',
  'issue.sighting.remove': 'edit',
  'issue.status': 'edit',
  'issue.merge': 'edit',
  'issue.recode': 'edit',
  'comment.add': 'comment.team',
  'comment.edit': 'comment.team',
  'comment.delete': 'comment.team',
  'comment.redact': 'admin',
  'assign.set': 'assign',
  'approval.add': 'approve',
  'approval.withdraw': 'approve',
  'change.review': 'edit',
  'detection.review': 'edit',
  'procmodel.part': 'edit',
  'manifest.entry': 'builder.edit',
  'boundary.edit': 'edit',
  'narrative.version': 'edit',
  'blob.add': 'builder.edit',
  'member.add': 'admin',
  'member.role': 'admin',
  'member.remove': 'admin',
  'member.link': 'admin',
  'device.revoke': 'admin',
  'policy.set': 'admin',
  'project.share': 'admin',
  'package.export': 'export.package',
  'exchange.import': null,
  'conflict.resolve': 'edit',
  'record.external': null,
  checkpoint: null,
  'journal.off': 'admin',
  'journal.on': null,
  'op.redact': 'admin',
};
export const JournalPolicy = z.object({
  defaultOn: z.boolean().default(true),
  allowOffPrivate: z.boolean().default(true),
  allowOffTeam: z.boolean().default(false),
});
export const DEFAULT_JOURNAL_POLICY = JournalPolicy.parse({});
export const Checkpoint = z.looseObject({
  schema: z.literal(CHECKPOINT_SCHEMA),
  chain: ChainId,
  dev: DeviceId,
  act: ActorId,
  hlc: Hlc,
  seq: Seq,
  heads: z.record(
    ChainId,
    z.looseObject({
      seq: Seq,
      id: OpId,
    }),
  ),
  count: z.number().int().nonnegative(),
  root: Sha256Hex,
  id: Sha256Hex,
  sig: SignatureB64.optional(),
});
export function checkpointFileName(hlc, chain) {
  const [ms, counter] = hlc.split('.');
  return `${ms ?? '0'}.${counter ?? '0'}.${chain}.json`;
}
export function segmentFileName(n) {
  return `${String(n).padStart(6, '0')}.jsonl`;
}
export const EditCommand = z.object({
  label: z.string().min(1).max(200),
  ids: z.array(Id).max(10_000),
  via: Via.optional(),
});
export const ChangeHow = z.enum(['hand', 'agent', 'pipeline', 'external', 'import', 'server']);
export const AuditEntry = z.object({
  op: OpId,
  chain: ChainId,
  seq: Seq,
  hlc: Hlc,
  at: IsoTime,
  actor: z.object({
    id: ActorId,
    name: z.string().optional(),
    initials: z.string().optional(),
  }),
  device: DeviceId,
  kind: OpKindName,
  target: RecordRef,
  label: z.string().optional(),
  how: ChangeHow,
  via: Via.optional(),
  changes: z
    .array(
      z.object({
        field: z.string(),
        before: z.unknown().optional(),
        after: z.unknown().optional(),
      }),
    )
    .optional(),
  state: z.enum(['ok', 'unsigned', 'quarantined', 'bad-signature', 'unknown-kind']),
  redacted: z
    .object({
      by: ActorId,
      at: Hlc,
    })
    .optional(),
});
export const AuditFilter = z.object({
  actors: z.array(ActorId).optional(),
  kinds: z.array(OpKindName).optional(),
  target: RecordRef.optional(),
  how: z.array(ChangeHow).optional(),
  from: IsoTime.optional(),
  to: IsoTime.optional(),
});
export const VerifyCode = z.enum([
  'parse',
  'hash-mismatch',
  'payload-hash',
  'payload-missing',
  'chain-gap',
  'order',
  'truncated',
  'segment-missing',
  'fork',
  'bad-signature',
  'unsigned',
  'unknown-device',
  'revoked-device',
  'checkpoint-mismatch',
  'clock-ahead',
]);
export const VerifyProblem = z.object({
  code: VerifyCode,
  file: z.string().optional(),
  line: z.number().int().min(1).optional(),
  chain: ChainId.optional(),
  seq: Seq.optional(),
  op: OpId.optional(),
  message: z.string(),
});
export const VerifyReport = z.object({
  ok: z.boolean(),
  checkedAt: IsoTime,
  head: z
    .object({
      root: Sha256Hex,
      count: z.number().int().nonnegative(),
    })
    .nullable(),
  chains: z.array(
    z.object({
      chain: ChainId,
      device: DeviceId,
      ops: z.number().int().nonnegative(),
      segments: z.number().int().nonnegative(),
      head: z
        .object({
          seq: Seq,
          id: OpId,
        })
        .nullable(),
    }),
  ),
  counts: z.object({
    ops: z.number().int().nonnegative(),
    signed: z.number().int().nonnegative(),
    unsigned: z.number().int().nonnegative(),
    external: z.number().int().nonnegative(),
    quarantined: z.number().int().nonnegative(),
    redacted: z.number().int().nonnegative(),
  }),
  problems: z.array(VerifyProblem),
});
export const AuditExportFormat = z.enum(['audit-csv', 'audit-json']);
export const AUDIT_FILE_SCHEMA = 'aio.audit/1';
export const AuditFile = z.looseObject({
  schema: z.literal(AUDIT_FILE_SCHEMA),
  app: z.object({
    name: z.string(),
    version: z.string(),
  }),
  project: z.object({
    name: z.string(),
  }),
  exportedAt: IsoTime,
  filter: AuditFilter.optional(),
  head: z
    .object({
      root: Sha256Hex,
      count: z.number().int().nonnegative(),
    })
    .nullable(),
  verify: VerifyReport.nullable(),
  entries: z.array(AuditEntry),
  journal: z.record(z.string(), z.string()),
});
export function isKnownOpKind(kind) {
  return OP_KINDS.includes(kind);
}
