// Generated by tools/compat/extract-schema.mjs from packages/schema/src/launch.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
export const LAUNCH_SETTINGS_FILE = 'launch.json';
export const LAUNCH_SETTINGS_SCHEMA = 'aio.launch-settings/1';
export const LaunchSettings = z.looseObject({
  schema: z.literal(LAUNCH_SETTINGS_SCHEMA),
  show: z.boolean().optional(),
});
export const defaultLaunchSettings = () => ({
  schema: LAUNCH_SETTINGS_SCHEMA,
});
export const launchScreenShown = (s) => s.show !== false;
