// Generated by tools/compat/extract-schema.mjs from packages/schema/src/manifest.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Id, IsoDate, Vec3, err, ok, uniqueIds } from './common.mjs';
import { Layer } from './layers.mjs';
import { ClassCatalogue, SeverityModel } from './severity.mjs';
import { ProjectType, VerticalDatum } from './builder.mjs';
export const SCHEMA_VERSION = 'aio.project/1';
export const Capture = z.object({
  id: Id,
  label: z.string().min(1),
  date: IsoDate,
});
export const Crs = z.union([
  z
    .object({
      epsg: z.number().int(),
    })
    .strict(),
  z
    .object({
      wkt: z.string().min(1),
    })
    .strict(),
]);
export const ProjectManifest = z
  .object({
    schema: z.literal(SCHEMA_VERSION),
    id: Id,
    name: z.string().min(1),
    customer: z.string().optional(),
    site: z.string().optional(),
    crs: Crs,
    origin: Vec3,
    captures: z.array(Capture),
    layers: z.array(Layer),
    severityModels: z.array(SeverityModel),
    classCatalogues: z.array(ClassCatalogue),
    brand: z.string().optional(),
    type: ProjectType.optional(),
    verticalDatum: VerticalDatum.optional(),
    aiCloudDrawings: z.boolean().optional(),
  })
  .superRefine(uniqueIds('layers'))
  .superRefine(uniqueIds('severityModels'))
  .superRefine(uniqueIds('captures'));
export const LAYER_KINDS = new Set(Layer.options.map((o) => o.shape.kind.value));
export const OpaqueLayer = z.looseObject({
  kind: z.string().min(1).max(64),
  id: Id,
  name: z.string().min(1),
});
const isRecord = (v) => typeof v === 'object' && v !== null && !Array.isArray(v);
function splitLayers(json) {
  const layers = json.layers;
  if (!Array.isArray(layers))
    return {
      known: json,
      unknown: [],
    };
  const kept = [];
  const unknown = [];
  for (const l of layers) {
    const kind = isRecord(l) ? l.kind : undefined;
    const opaque = typeof kind === 'string' && !LAYER_KINDS.has(kind) && OpaqueLayer.safeParse(l);
    if (opaque && opaque.success) unknown.push(opaque.data);
    else kept.push(l);
  }
  return {
    known: {
      ...json,
      layers: kept,
    },
    unknown,
  };
}
export function parseManifestTolerant(json) {
  if (!isRecord(json)) return err('Project manifest is not a JSON object.');
  const version = json.schema;
  if (
    typeof version === 'string' &&
    version !== SCHEMA_VERSION &&
    version.startsWith('aio.project/')
  ) {
    return err(
      `Project was saved by a newer version of Quadrion AI (schema ${version}). Update the app to open it.`,
    );
  }
  const { known, unknown } = splitLayers(json);
  const r = ProjectManifest.safeParse(known);
  if (!r.success) {
    const first = r.error.issues[0];
    const where = first?.path.length ? ` at ${first.path.join('.')}` : '';
    return err(`Project manifest is invalid${where}: ${first?.message ?? 'unknown error'}`);
  }
  const ids = new Set(r.data.layers.map((l) => l.id));
  for (const u of unknown) {
    if (ids.has(u.id))
      return err(`Project manifest is invalid at layers: Duplicate id "${u.id}" in layers`);
    ids.add(u.id);
  }
  return ok({
    manifest: r.data,
    unknownLayers: unknown,
  });
}
export function parseManifest(json) {
  const r = parseManifestTolerant(json);
  return r.ok ? ok(r.value.manifest) : r;
}
export function unknownLayersOf(json) {
  return isRecord(json) ? splitLayers(json).unknown : [];
}
export function keepUnknownLayers(previous, next) {
  const unknown = unknownLayersOf(previous);
  if (unknown.length === 0) return ok(next);
  const ids = new Set(next.layers.map((l) => l.id));
  const taken = unknown.find((u) => ids.has(u.id));
  if (taken) {
    return err(
      `Layer id "${taken.id}" is used by a layer from a newer version of Quadrion AI (${taken.kind}). Choose another id.`,
    );
  }
  return ok({
    ...next,
    layers: [...next.layers, ...unknown],
  });
}
