// Generated by tools/compat/extract-schema.mjs from packages/schema/src/orientation.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Id, IsoTime, Vec3 } from './common.mjs';
export const ORIENTATION_SCHEMA = 'aio.orientation/1';
export const DIRECTION_FILLS = ['smooth', 'track', 'lookAt'];
export const DirectionFill = z.enum(DIRECTION_FILLS);
export const DirectionKey = z
  .object({
    t: z.number().nonnegative(),
    yaw: z.number().min(-360).max(360),
    pitch: z.number().min(-90).max(90),
    roll: z.number().min(-180).max(180),
    fill: z.string().min(1).max(32),
    target: Vec3.optional(),
  })
  .refine((k) => k.fill !== 'lookAt' || k.target !== undefined, {
    message: 'A look-at keyframe needs a target',
    path: ['target'],
  });
export const DirectionKeys = z
  .array(DirectionKey)
  .max(1000)
  .refine((ks) => ks.every((k, i) => i === 0 || k.t > (ks[i - 1]?.t ?? -1)), {
    message: 'Direction keyframes must be in time order, one per time',
  });
export const PhotoCorrection = z.object({
  yawDeg: z.number().min(-180).max(180),
  pitchDeg: z.number().min(-90).max(90),
  rollDeg: z.number().min(-180).max(180),
  offsetM: Vec3.optional(),
});
export const ClipDirection = z.object({
  keys: DirectionKeys,
});
export const OrientationFile = z.object({
  schema: z.literal(ORIENTATION_SCHEMA),
  updatedAt: IsoTime.optional(),
  clips: z.record(Id, ClipDirection).default({}),
  photos: z.record(Id, z.record(Id, PhotoCorrection)).default({}),
});
export function emptyOrientation() {
  return {
    schema: ORIENTATION_SCHEMA,
    clips: {},
    photos: {},
  };
}
