// Generated by tools/compat/extract-schema.mjs from packages/schema/src/photogrammetry.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { LonLatRing } from './change.mjs';
import { Id, IsoTime, ProjectPath, Vec3 } from './common.mjs';
import { Crs } from './manifest.mjs';
export const PhotoRunId = z
  .string()
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/, 'A run id is letters, digits, dot, dash or _.');
export const PHOTO_DIR = 'photogrammetry';
export const photoRunDir = (run) => `${PHOTO_DIR}/${run}`;
export const PHOTO_RUN_FILES = {
  run: 'run.json',
  gcp: 'gcp.json',
  accuracy: 'report/accuracy.json',
  align: 'report/align.json',
  products: 'report/products.json',
  camerasSfm: 'cameras-sfm.json',
  sparse: 'sparse/',
  work: 'work/',
};
export const PhotoPreset = z.enum(['fast', 'standard', 'high']);
export const PhotoProduct = z.enum(['cloud', 'dsm', 'dtm', 'ortho', 'mesh', 'tiles']);
export const PhotoSource = z.union([
  z
    .object({
      layer: Id,
    })
    .strict(),
  z
    .object({
      folders: z.array(z.string().min(1).max(1024)).min(1).max(100),
    })
    .strict(),
]);
export const PhotoStageName = z.enum([
  'inspect',
  'features',
  'match',
  'sfm',
  'georef',
  'adjust',
  'report',
  'dense',
  'fuse',
  'cloud',
  'dsm',
  'dtm',
  'ortho',
  'mesh',
  'texture',
  'tiles',
  'commit',
]);
export const PhotoStage = z.looseObject({
  name: PhotoStageName,
  state: z.enum(['pending', 'running', 'done', 'skipped', 'failed', 'cancelled']),
  startedAt: IsoTime.optional(),
  finishedAt: IsoTime.optional(),
  seconds: z.number().nonnegative().optional(),
  memoryPeakBytes: z.number().int().nonnegative().optional(),
  message: z.string().max(2000).optional(),
});
export const PhotoCameraGroup = z.looseObject({
  id: Id,
  make: z.string().max(120).optional(),
  model: z.string().max(120).optional(),
  widthPx: z.number().int().positive(),
  heightPx: z.number().int().positive(),
  focalMm: z.number().positive().optional(),
  sensorWidthMm: z.number().positive().optional(),
  calibration: z.string().max(40).optional(),
  photos: z.number().int().nonnegative(),
});
export const PhotoHeights = z.looseObject({
  source: z.enum(['ellipsoidal', 'orthometric', 'relative', 'gcp']),
  geoid: z.enum(['egm96', 'egm2008', 'none']).optional(),
  absAltOffsetM: z.number().optional(),
  note: z.string().max(300).optional(),
});
export const PhotoRejected = z.looseObject({
  name: z.string().min(1).max(260),
  reason: z.string().min(1).max(300),
});
export const Rmse = z.object({
  n: z.number().int().nonnegative(),
  horizontalM: z.number().nonnegative(),
  verticalM: z.number().nonnegative(),
});
export const AccuracySummary = z.looseObject({
  control: Rmse.optional(),
  check: Rmse.optional(),
  meanReprojPx: z.number().nonnegative(),
  gsdCm: z.number().positive().optional(),
  warnings: z.number().int().nonnegative().optional(),
});
export const HardwareProbe = z.looseObject({
  platform: z.string().min(1).max(40),
  arch: z.string().min(1).max(40),
  cpu: z.object({
    model: z.string().max(200),
    cores: z.number().int().positive(),
    threads: z.number().int().positive().optional(),
  }),
  memoryBytes: z.number().int().nonnegative(),
  freeDiskBytes: z.number().int().nonnegative(),
  gpus: z
    .array(
      z.object({
        name: z.string().max(200),
        vendor: z.string().max(80).optional(),
        vramBytes: z.number().int().nonnegative().optional(),
      }),
    )
    .max(16),
  cuda: z.boolean(),
  processing: z.enum(['available', 'unsupported-platform', 'pack-too-old', 'no-pack']),
});
export const PhotoEstimate = z.object({
  minutes: z.tuple([z.number().nonnegative(), z.number().nonnegative()]),
  diskBytes: z.number().int().nonnegative(),
  memoryBytes: z.number().int().nonnegative(),
  notes: z.array(z.string().max(300)).max(20).optional(),
  cameras: z.array(PhotoCameraGroup).max(100).optional(),
  suggestedEpsg: z.number().int().positive().optional(),
});
export const PhotoRun = z.looseObject({
  schema: z.literal('aio.photo-run/1'),
  id: PhotoRunId,
  createdAt: IsoTime,
  updatedAt: IsoTime.optional(),
  status: z.enum(['aligning', 'aligned', 'adjusted', 'processing', 'done', 'failed', 'cancelled']),
  preset: PhotoPreset,
  photos: z.looseObject({
    source: PhotoSource,
    count: z.number().int().nonnegative(),
    registered: z.number().int().nonnegative().optional(),
    rejected: z.array(PhotoRejected).max(100_000).optional(),
  }),
  cameras: z.array(PhotoCameraGroup).max(100),
  crs: Crs,
  heights: PhotoHeights.optional(),
  settings: z.record(z.string(), z.unknown()).optional(),
  region: LonLatRing.optional(),
  capture: Id.optional(),
  stages: z.array(PhotoStage).max(64),
  outputs: z.looseObject({
    layers: z.array(Id).max(64),
    tilesets: z.array(Id).max(64),
    files: z.array(ProjectPath).max(256),
  }),
  accuracy: AccuracySummary.optional(),
  versions: z.record(z.string().min(1).max(40), z.string().max(80)),
  hardware: HardwareProbe.optional(),
  warnings: z.array(z.string().max(500)).max(1000).optional(),
});
export const GcpRole = z.enum(['control', 'check']);
export const GcpMarkState = z.enum(['draft', 'confirmed', 'skipped']);
export const GcpMark = z.looseObject({
  photo: z.string().min(1).max(260),
  px: z.tuple([z.number(), z.number()]),
  by: z.enum(['person', 'detector', 'import']),
  at: IsoTime,
  state: GcpMarkState,
});
export const GcpPrediction = z.looseObject({
  photo: z.string().min(1).max(260),
  px: z.tuple([z.number(), z.number()]),
  radiusPx: z.number().nonnegative(),
});
export const GcpPoint = z.looseObject({
  id: z.string().min(1).max(64),
  label: z.string().max(120).optional(),
  role: GcpRole,
  xyz: Vec3,
  accuracy: z.object({
    horizontalM: z.number().positive(),
    verticalM: z.number().positive(),
  }),
  disabled: z.boolean().optional(),
  marks: z.array(GcpMark).max(10_000),
  predicted: z.array(GcpPrediction).max(10_000).optional(),
});
export const GcpFile = z
  .looseObject({
    schema: z.literal('aio.gcp/1'),
    crs: Crs,
    heights: PhotoHeights.optional(),
    importedFrom: z.string().max(260).optional(),
    points: z.array(GcpPoint).max(1000),
  })
  .superRefine((f, ctx) => {
    const seen = new Set();
    for (const p of f.points) {
      if (seen.has(p.id))
        ctx.addIssue({
          code: 'custom',
          message: `Duplicate point "${p.id}"`,
          path: ['points'],
        });
      seen.add(p.id);
    }
  });
export const AccuracyPoint = z.looseObject({
  id: z.string().min(1).max(64),
  role: GcpRole,
  dxM: z.number(),
  dyM: z.number(),
  dzM: z.number(),
  reprojPx: z.number().nonnegative(),
  marks: z.number().int().nonnegative(),
  usedInAdjustment: z.boolean().optional(),
});
export const AccuracyWarning = z.looseObject({
  code: z.enum([
    'gcp-outlier',
    'few-marks',
    'gnss-height',
    'unregistered',
    'disconnected',
    'low-overlap',
    'other',
  ]),
  message: z.string().min(1).max(500),
  point: z.string().max(64).optional(),
});
export const AccuracyReport = z.looseObject({
  schema: z.literal('aio.photo-accuracy/1'),
  run: PhotoRunId,
  createdAt: IsoTime,
  crs: Crs,
  heights: PhotoHeights.optional(),
  gsdCm: z.number().positive().optional(),
  images: z.object({
    total: z.number().int().nonnegative(),
    registered: z.number().int().nonnegative(),
  }),
  meanReprojPx: z.number().nonnegative(),
  points: z.array(AccuracyPoint).max(1000),
  rmse: z.object({
    control: Rmse.optional(),
    check: Rmse.optional(),
  }),
  cameraResiduals: z
    .object({
      medianM: z.number().nonnegative(),
      maxM: z.number().nonnegative(),
      rmseHorizontalM: z.number().nonnegative(),
      rmseVerticalM: z.number().nonnegative(),
    })
    .optional(),
  overlap: ProjectPath.optional(),
  checkpointsInAdjustment: z.literal(false),
  warnings: z.array(AccuracyWarning).max(1000),
});
export const PhotoCalibration = z.looseObject({
  id: z.string().min(1).max(64),
  model: z.string().min(1).max(40),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  params: z.array(z.number()).max(32),
});
export const PhotoSfmCamera = z.looseObject({
  photo: z.string().min(1).max(1024),
  pos: Vec3,
  q: z.tuple([z.number(), z.number(), z.number(), z.number()]),
  lens: z.looseObject({
    model: z.string().min(1).max(40),
    hfovDeg: z.number().positive().max(360),
    aspect: z.number().positive(),
  }),
  camera: z.string().min(1).max(64).optional(),
});
export const PhotoCamerasFile = z.looseObject({
  schema: z.literal('aio.photo-cameras/1'),
  run: PhotoRunId,
  crs: Crs,
  origin: Vec3,
  frame: z.string().max(200).optional(),
  calibration: z.array(PhotoCalibration).max(100),
  cameras: z.array(PhotoSfmCamera).max(100_000),
});
export const PhotoRunSummary = z.object({
  id: PhotoRunId,
  createdAt: IsoTime,
  status: PhotoRun.shape.status,
  preset: PhotoPreset,
  photos: z.number().int().nonnegative(),
  products: z.array(PhotoProduct),
  accuracy: AccuracySummary.optional(),
});
