// Generated by tools/compat/extract-schema.mjs from packages/schema/src/report.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { IsoTime } from './common.mjs';
export const NARRATIVE_SCHEMA = 'aio.narrative/1';
export const NarrativeSectionId = z.enum(['summary', 'method', 'findings']);
export const NARRATIVE_SECTIONS = NarrativeSectionId.options;
export const NarrativeVersion = z
  .object({
    text: z.string().max(20_000),
    source: z.enum(['ai', 'template', 'user']),
    createdAt: IsoTime,
    author: z.string().max(200).optional(),
    provider: z.string().max(64).optional(),
    model: z.string().max(128).optional(),
  })
  .strict();
export const NARRATIVE_MAX_VERSIONS = 50;
export const NarrativePart = z
  .object({
    versions: z.array(NarrativeVersion).max(NARRATIVE_MAX_VERSIONS),
  })
  .strict();
export const NarrativeFile = z
  .object({
    schema: z.literal(NARRATIVE_SCHEMA),
    parts: z.partialRecord(NarrativeSectionId, NarrativePart),
  })
  .strict();
export const ReportSectionId = z.enum([
  'contents',
  'summary',
  'scope',
  'site',
  'statistics',
  'register',
  'issues',
  'appendices',
  'audit',
  'approvals',
  'processing',
]);
export const REPORT_SECTIONS = ReportSectionId.options;
export const IssuePagesRule = z.enum(['all', 'above-lowest', 'none']);
export const ReportContentsSettings = z
  .object({
    sections: z.partialRecord(ReportSectionId, z.boolean()).optional(),
    issuePages: IssuePagesRule.optional(),
  })
  .strict();
export function emptyNarrative() {
  return {
    schema: NARRATIVE_SCHEMA,
    parts: {},
  };
}
export function currentNarrative(file, id) {
  const v = file?.parts[id]?.versions.at(-1);
  return v ? v.text : null;
}
export function addNarrativeVersion(file, id, version) {
  const base = file ?? emptyNarrative();
  const versions = base.parts[id]?.versions ?? [];
  const last = versions.at(-1);
  if (last?.text === version.text && last.source === version.source) return base;
  const next = [...versions, version].slice(-NARRATIVE_MAX_VERSIONS);
  return {
    ...base,
    parts: {
      ...base.parts,
      [id]: {
        versions: next,
      },
    },
  };
}
export function reportSectionOn(contents, id) {
  return contents?.sections?.[id] ?? true;
}
