// Generated by tools/compat/extract-schema.mjs from packages/schema/src/tilesets.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Id, IsoTime, Mat4, ProjectPath } from './common.mjs';
import { PhotoRunId } from './photogrammetry.mjs';
export const TilesetId = z
  .string()
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/, 'A tileset id is letters, digits, dot, dash or _.');
export const TILESETS_FILE = 'tilesets.json';
export const TILES_DIR = 'tiles';
export const TilesetKind = z.enum(['mesh', 'points', 'terrain', 'imported']);
export const TilesetEntry = z.looseObject({
  id: TilesetId,
  name: z.string().min(1).max(200),
  kind: TilesetKind,
  src: ProjectPath,
  from: Id.optional(),
  run: PhotoRunId.optional(),
  capture: Id.optional(),
  visible: z.boolean(),
  transform: Mat4.optional(),
  confirmedAt: IsoTime.optional(),
  attribution: z.string().max(500).optional(),
});
export const TilesetsFile = z
  .looseObject({
    schema: z.literal('aio.tilesets/1'),
    entries: z.array(TilesetEntry).max(500),
  })
  .superRefine((f, ctx) => {
    const seen = new Set();
    for (const e of f.entries) {
      if (seen.has(e.id))
        ctx.addIssue({
          code: 'custom',
          message: `Duplicate tileset "${e.id}"`,
          path: ['entries'],
        });
      seen.add(e.id);
    }
  });
export const emptyTilesets = () => ({
  schema: 'aio.tilesets/1',
  entries: [],
});
