// Generated by tools/compat/extract-schema.mjs from packages/schema/src/volumes.ts at e422fd3 (Stratlas 0.10). Do not edit.
import { z } from 'zod';
import { Id, IsoDate, IsoTime, Vec2 } from './common.mjs';
export const VolumeBaseId = z.enum(['tin', 'plane', 'avg', 'low']);
export const FillCut = z.object({
  fill: z.number(),
  cut: z.number(),
  net: z.number(),
});
export const BaseVolumes = z.object({
  tin: FillCut,
  plane: FillCut,
  avg: FillCut,
  low: FillCut,
});
const RingXZ = z.array(Vec2);
export const PileEpoch = z
  .object({
    captureId: Id,
    areaM2: z.number().nonnegative(),
    topM: z.number(),
    heightM: z.number(),
    surveyErrM3: z.number().optional(),
    groundToeFrac: z.number().optional(),
    node: z.string().optional(),
    ring: RingXZ,
    volumes: BaseVolumes,
  })
  .loose();
export const StockPile = z
  .object({
    id: Id,
    name: z.string(),
    material: z.string().nullable().optional(),
    status: z.string().optional(),
    centreEN: Vec2.optional(),
    zoneRing: RingXZ,
    change: FillCut,
    epochs: z.record(z.string(), PileEpoch),
  })
  .loose();
export const VolumeCapture = z
  .object({
    epoch: Id,
    captureId: Id,
    date: IsoDate,
    label: z.string(),
    layers: z.array(Id).optional(),
  })
  .loose();
export const VolumeGrids = z.object({
  format: z.literal('vs-kit-js'),
  piles: z.string().min(1),
  dsm: z.string().min(1),
  coarse: z.string().min(1).optional(),
});
export const VolumesFile = z
  .object({
    schema: z.literal('aio.volumes/1'),
    source: z.string().optional(),
    densityTPerM3: z.number().positive(),
    swell: z.number().positive().optional(),
    deadbandM: z.number().nonnegative(),
    defaultBase: VolumeBaseId,
    bases: z
      .array(
        z.object({
          id: VolumeBaseId,
          label: z.string(),
        }),
      )
      .min(1),
    captures: z.array(VolumeCapture).min(1),
    piles: z.array(StockPile),
    totals: z.record(z.string(), z.record(z.string(), z.number())),
    pileChange: FillCut,
    siteChange: FillCut.extend({
      area_m2: z.number().optional(),
    }).loose(),
    aoi: RingXZ.nullable().optional(),
    excluded: z
      .array(
        z
          .object({
            reason: z.string(),
            ring: RingXZ,
          })
          .loose(),
      )
      .optional(),
    grids: VolumeGrids.optional(),
  })
  .loose();
export const BoundaryEdit = z
  .object({
    pile: Id,
    epoch: Id,
    ring: RingXZ.min(3),
    volumes: BaseVolumes,
    areaM2: z.number().nonnegative(),
    topM: z.number(),
    heightM: z.number(),
    autoNet: z.number(),
    author: z.string().optional(),
    updatedAt: IsoTime,
  })
  .strict();
export const BoundaryEditsFile = z
  .object({
    schema: z.literal('aio.boundaries/1'),
    edits: z.array(BoundaryEdit),
  })
  .strict()
  .superRefine((value, ctx) => {
    const seen = new Set();
    for (const e of value.edits) {
      const key = `${e.pile}/${e.epoch}`;
      if (seen.has(key))
        ctx.addIssue({
          code: 'custom',
          message: `Two edits of ${key}`,
          path: ['edits'],
        });
      seen.add(key);
    }
  });
