// Generated by tools/compat/extract-schema.mjs from packages/schema/src/builder.ts at 91770f2 (Stratlas 0.9). Do not edit.
import { z } from 'zod';
import { Id, IsoDate, Mat4, Vec3 } from './common.mjs';
import { CameraOrientation, LensModel } from './layers.mjs';
import { ClassCatalogue, SeverityModel } from './severity.mjs';
export const ProjectType = z.enum(['inspection', 'volumetric', 'road', 'twin', 'fusion']);
export const SeverityTemplate = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  source: z.string(),
  model: SeverityModel,
  catalogue: ClassCatalogue.optional(),
});
export const VerticalDatum = z
  .object({
    absAltOffsetM: z.number().min(-2000).max(2000),
    note: z.string().max(300).optional(),
  })
  .strict();
export const AltitudeSource = z.enum(['absolute', 'relative', 'none']);
export const FlightHeights = z.object({
  source: z.enum(['absolute', 'relative', 'none', 'mixed']),
  absOffsetM: z.number(),
  takeoffH: z.number(),
});
export const AltitudeChoice = z
  .object({
    source: z.enum(['auto', 'absolute', 'relative']),
    takeoffH: z.number().min(-1000).max(10000).optional(),
    takeoffFrom: z.enum(['terrain', 'typed', 'origin']).optional(),
    absAltOffsetM: z.number().min(-2000).max(2000).optional(),
  })
  .strict();
export const ImportHeights = z.object({
  source: z.enum(['absolute', 'relative']),
  offsetM: z.number(),
  from: z.enum(['datum', 'uncorrected', 'terrain', 'typed', 'origin']),
  note: z.string().optional(),
});
export const AltitudePlan = z.object({
  files: z.number().int().nonnegative(),
  absolute: z.number().int().nonnegative(),
  relative: z.number().int().nonnegative(),
  datum: VerticalDatum.nullable(),
  recommended: z.enum(['absolute', 'relative']),
  takeoff: z
    .object({
      x: z.number(),
      z: z.number(),
      relAltM: z.number(),
    })
    .nullable(),
  takeoffAbsAlt: z.number().nullable(),
});
export const ReportBrand = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
});
export const NewProjectRequest = z
  .object({
    name: z.string().trim().min(1).max(120),
    customer: z.string().trim().max(120).optional(),
    site: z.string().trim().max(200).optional(),
    type: ProjectType,
    epsg: z.number().int(),
    origin: Vec3,
    captureDate: IsoDate.optional(),
    severityTemplate: z.string().min(1).nullable(),
    brand: z.string().min(1).optional(),
    verticalDatum: VerticalDatum.optional(),
  })
  .strict();
export const ImportItem = z.object({
  file: z.string(),
  kind: z.enum([
    'photo',
    'video',
    'telemetry',
    'mesh',
    'raster',
    'pointcloud',
    'unknown',
    'drawing',
  ]),
  status: z.enum(['imported', 'skipped', 'needs-pipeline', 'queued', 'error']),
  message: z.string().optional(),
  layerId: z.string().optional(),
  jobId: z.string().optional(),
  heightSource: z.enum(['absolute', 'relative', 'none', 'mixed']).optional(),
});
export const LayerPatch = z.union([
  z
    .object({
      transform: Mat4,
    })
    .strict(),
  z
    .object({
      offsetMs: z.number().optional(),
      lens: LensModel.optional(),
      orientation: CameraOrientation.nullable().optional(),
      positionOffsetM: Vec3.nullable().optional(),
    })
    .strict()
    .refine(
      (p) =>
        p.offsetMs !== undefined ||
        p.lens !== undefined ||
        p.orientation !== undefined ||
        p.positionOffsetM !== undefined,
      {
        message: 'Give offsetMs, lens, orientation or positionOffsetM',
      },
    ),
  z
    .object({
      capture: Id.nullable(),
    })
    .strict(),
]);
