// Generated by tools/compat/extract-schema.mjs from packages/schema/src/collab.ts at 91770f2 (Stratlas 0.9). Do not edit.
import { z } from 'zod';
import { Hlc, IsoDate, Sha256Hex, Vec3 } from './common.mjs';
import { ActorId, VerificationLevel } from './identity.mjs';
export const CollabTargetKind = z.enum([
  'issue',
  'change-item',
  'change-set',
  'detection-pass',
  'part',
  'model',
  'report',
  'project',
]);
export const CollabTarget = z.object({
  kind: CollabTargetKind,
  id: z.string().min(1).max(300),
  in: z.string().min(1).max(300).optional(),
});
export const CommentId = z
  .string()
  .regex(/^cm_[a-z2-7]{16}$/, 'A comment id is cm_ and 16 base32 letters.');
export const ApprovalId = z
  .string()
  .regex(/^ap_[a-z2-7]{16}$/, 'An approval id is ap_ and 16 base32 letters.');
export const CommentVisibility = z.enum(['team', 'client']);
export const SavedView = z.object({
  camera: z.object({
    position: Vec3,
    target: Vec3,
    fovDeg: z.number().positive().max(179).optional(),
  }),
  time: z.number().nonnegative().optional(),
  capture: z.string().min(1).max(128).optional(),
  layer: z.string().min(1).max(128).optional(),
});
export const CommentText = z.string().trim().min(1).max(10_000);
export const CommentPayload = z.object({
  id: CommentId,
  target: CollabTarget,
  text: CommentText,
  visibility: CommentVisibility.default('team'),
  mentions: z.array(ActorId).max(50).default([]),
  view: SavedView.optional(),
  replyTo: CommentId.optional(),
});
export const CommentEditPayload = z.object({
  id: CommentId,
  text: CommentText,
  mentions: z.array(ActorId).max(50).optional(),
});
export const CommentDeletePayload = z.object({
  id: CommentId,
});
export const CommentRedactPayload = z.object({
  id: CommentId,
  ops: z.array(Sha256Hex).min(1).max(100),
  reason: z.string().max(500).optional(),
});
export const AssignPayload = z.object({
  target: CollabTarget,
  assignee: ActorId.nullable(),
  due: IsoDate.optional(),
  note: z.string().max(2000).optional(),
});
export const ApprovalDecision = z.enum(['approve', 'changes-requested', 'accept']);
export const ApprovalPayload = z
  .object({
    id: ApprovalId,
    target: CollabTarget,
    decision: ApprovalDecision,
    contentHash: Sha256Hex,
    comment: z.string().max(10_000).optional(),
  })
  .refine((p) => p.decision !== 'changes-requested' || (p.comment ?? '').trim() !== '', {
    message: 'Request changes needs a comment.',
    path: ['comment'],
  });
export const ApprovalWithdrawPayload = z.object({
  id: ApprovalId,
});
export const MaterialField = z.enum([
  'class',
  'severity',
  'sightings',
  'measurements',
  'status',
  'title',
  'note',
]);
export const ApprovalPolicy = z.object({
  required: z.number().int().min(1).max(5).default(1),
  fourEyes: z.boolean().default(true),
  closeBy: z.enum(['owner', 'owner-or-reviewer']).default('owner'),
  viewersMayComment: z.boolean().default(false),
  clientAcceptance: z.enum(['record', 'off']).default('record'),
  materialFields: z
    .array(MaterialField)
    .default(['class', 'severity', 'sightings', 'measurements', 'status']),
});
export const TeamPolicy = z.object({
  approval: ApprovalPolicy.default(ApprovalPolicy.parse({})),
  minVerification: VerificationLevel.default('self'),
  packageHistory: z.enum(['summary', 'full']).default('summary'),
});
export const PolicySetPayload = z.object({
  approval: ApprovalPolicy.partial().optional(),
  minVerification: VerificationLevel.optional(),
  packageHistory: z.enum(['summary', 'full']).optional(),
});
export const DEFAULT_APPROVAL_POLICY = ApprovalPolicy.parse({});
export const DEFAULT_TEAM_POLICY = TeamPolicy.parse({});
export const CommentView = z.object({
  id: CommentId,
  target: CollabTarget,
  author: ActorId,
  text: z.string().nullable(),
  visibility: CommentVisibility,
  mentions: z.array(ActorId),
  view: SavedView.optional(),
  replyTo: CommentId.optional(),
  createdAt: Hlc,
  editedAt: Hlc.optional(),
  versions: z.number().int().min(1),
  deleted: z.boolean(),
  redacted: z
    .object({
      by: ActorId,
      at: Hlc,
    })
    .optional(),
});
export const AssignmentView = z.object({
  target: CollabTarget,
  assignee: ActorId,
  due: IsoDate.optional(),
  note: z.string().optional(),
  by: ActorId,
  at: Hlc,
});
export const ApprovalView = z.object({
  id: ApprovalId,
  target: CollabTarget,
  by: ActorId,
  decision: ApprovalDecision,
  contentHash: Sha256Hex,
  comment: z.string().optional(),
  at: Hlc,
  withdrawn: z.boolean(),
  current: z.boolean(),
});
export const CollabState = z.object({
  comments: z.array(CommentView),
  assignments: z.array(AssignmentView),
  approvals: z.array(ApprovalView),
  policy: TeamPolicy.nullable(),
});
export function targetKey(t) {
  return `${t.kind}:${t.in ?? ''}:${t.id}`;
}
