// Generated by tools/compat/extract-schema.mjs from packages/schema/src/conversation.ts at 91770f2 (Stratlas 0.9). Do not edit.
import { z } from 'zod';
import { ToolRisk, WindowKind } from './agent.mjs';
import { IsoTime } from './common.mjs';
export const CONVERSATION_SCHEMA = 'aio.conversation/1';
export const ConversationId = z
  .string()
  .regex(/^[A-Za-z0-9_-]{1,64}$/, 'Conversation ids are letters, digits, _ and -');
export const StepStatus = z.enum([
  'running',
  'awaiting',
  'done',
  'rejected',
  'error',
  'undone',
  'cancelled',
]);
export const ConversationStep = z.object({
  callId: z.string().min(1).max(128),
  name: z.string().min(1).max(64),
  input: z.unknown(),
  risk: ToolRisk,
  status: StepStatus,
  summary: z.string().max(500).optional(),
  canUndo: z.boolean(),
});
export const ConversationPart = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('text'),
    text: z.string(),
  }),
  z.object({
    type: z.literal('step'),
    callId: z.string().min(1).max(128),
  }),
]);
export const ConversationTurn = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('user'),
    id: z.string().min(1).max(128),
    text: z.string(),
    chips: z.array(z.string()),
    frame: z.boolean(),
  }),
  z.object({
    kind: z.literal('assistant'),
    id: z.string().min(1).max(128),
    runId: z.string().min(1).max(128),
    parts: z.array(ConversationPart),
    status: z.enum(['streaming', 'done', 'error', 'stopped']),
    error: z.string().optional(),
  }),
]);
export const ConversationUsage = z.object({
  inputTokens: z.number().nonnegative(),
  outputTokens: z.number().nonnegative(),
  costUsd: z.number().nonnegative(),
  costKnown: z.boolean(),
});
export const Conversation = z.object({
  schema: z.literal(CONVERSATION_SCHEMA),
  id: ConversationId,
  title: z.string().max(200),
  window: WindowKind,
  createdAt: IsoTime,
  updatedAt: IsoTime,
  turns: z.array(ConversationTurn).max(5000),
  steps: z.record(z.string(), ConversationStep),
  usage: ConversationUsage,
});
export const ConversationSummary = z.object({
  id: ConversationId,
  title: z.string(),
  window: WindowKind,
  createdAt: IsoTime,
  updatedAt: IsoTime,
  turns: z.number().int().nonnegative(),
  pending: z.number().int().nonnegative(),
});
