// Generated by tools/compat/extract-schema.mjs from packages/schema/src/exchange.ts at 91770f2 (Stratlas 0.9). Do not edit.
import { z } from 'zod';
import { Hlc, IsoTime, PublicKeyB64, Sha256Hex, SignatureB64 } from './common.mjs';
import { CollabTarget } from './collab.mjs';
import { ActorId, AppStamp, DeviceId, Initials, PersonName } from './identity.mjs';
import { ChainId, OpId, Seq } from './journal.mjs';
export const TEAM_SCHEMA = 'aio.team/1';
export const EXCHANGE_SCHEMA = 'aio.exchange/1';
export const HUB_SCHEMA = 'aio.hub/1';
export const PRESENCE_SCHEMA = 'aio.presence/1';
export const TEAM_FILE = 'team.json';
export const EXCHANGE_EXTENSION = '.aiosync';
export const EXCHANGE_HEADER_FILE = 'aio-exchange.json';
export const HUB_FILE = 'aio-hub.json';
export const PRESENCE_TTL_MS = 2 * 60 * 1000;
export const TeamProjectId = z
  .string()
  .regex(/^t_[a-z2-7]{26}$/, 'A team project id is t_ and 26 base32 letters.');
export const TeamProject = z.object({
  schema: z.literal(TEAM_SCHEMA),
  teamProjectId: TeamProjectId,
  name: z.string().min(1).max(200),
  createdAt: IsoTime,
  createdBy: ActorId,
});
export const Heads = z.record(
  ChainId,
  z.object({
    seq: Seq,
    id: OpId,
  }),
);
export const ExchangeKind = z.enum(['patch', 'bundle', 'reply']);
export const ExchangeId = z
  .string()
  .regex(/^x_[a-z2-7]{16}$/, 'An exchange id is x_ and 16 base32 letters.');
export const ExchangeHeader = z.looseObject({
  schema: z.literal(EXCHANGE_SCHEMA),
  id: ExchangeId,
  kind: ExchangeKind,
  teamProjectId: TeamProjectId,
  createdAt: IsoTime,
  from: z.object({
    actor: ActorId,
    device: DeviceId,
    name: PersonName,
    app: AppStamp,
  }),
  to: z
    .object({
      actors: z.array(ActorId).optional(),
      note: z.string().max(500).optional(),
    })
    .optional(),
  since: z.union([
    z.object({
      heads: Heads,
    }),
    z.object({
      date: IsoTime,
    }),
    z.object({
      all: z.literal(true),
    }),
  ]),
  chains: z.array(
    z.object({
      chain: ChainId,
      from: Seq,
      to: Seq,
      member: z.string().min(1),
    }),
  ),
  heads: Heads,
  blobs: z
    .array(
      z.object({
        sha256: Sha256Hex,
        size: z.number().int().nonnegative(),
      }),
    )
    .default([]),
  counts: z.object({
    ops: z.number().int().nonnegative(),
    devices: z.number().int().nonnegative(),
    blobs: z.number().int().nonnegative(),
    bytes: z.number().int().nonnegative(),
  }),
  package: z
    .object({
      projectId: z.string().min(1),
      createdAt: IsoTime,
    })
    .optional(),
  encrypted: z.boolean(),
  sig: SignatureB64,
});
export function opChunkName(from, to) {
  const six = (n) => String(n).padStart(6, '0');
  return `${six(from)}-${six(to)}.jsonl`;
}
export const ExchangePreview = z.object({
  file: z.string(),
  header: ExchangeHeader,
  signature: z.enum(['valid', 'invalid', 'unknown-device', 'revoked-device']),
  sender: z.object({
    name: z.string(),
    initials: z.string().optional(),
    member: z.boolean(),
  }),
  byKind: z.record(z.string(), z.number().int().nonnegative()),
  newOps: z.number().int().nonnegative(),
  alreadyHave: z.number().int().nonnegative(),
  held: z.array(
    z.object({
      chain: ChainId,
      device: DeviceId,
      upTo: Seq,
    }),
  ),
  expectedConflicts: z.number().int().nonnegative(),
  blobs: z.object({
    count: z.number().int().nonnegative(),
    bytes: z.number().int().nonnegative(),
    missing: z.number().int().nonnegative(),
  }),
  alreadyApplied: z.boolean(),
  problems: z.array(z.string()),
});
export const HubFile = z.looseObject({
  schema: z.literal(HUB_SCHEMA),
  id: z.string().regex(/^h_[a-z2-7]{16}$/),
  createdAt: IsoTime,
  projects: z
    .array(
      z.object({
        teamProjectId: TeamProjectId,
        name: z.string(),
      }),
    )
    .default([]),
});
export const HUB_PATHS = {
  project: (team) => `projects/${team}`,
  devices: (team) => `projects/${team}/devices`,
  ops: (team, chain) => `projects/${team}/ops/${chain}`,
  blobs: (team) => `projects/${team}/blobs`,
  presence: (team, device) => `projects/${team}/presence/${device}.json`,
  team: (team) => `projects/${team}/team.json`,
};
export const Presence = z.object({
  schema: z.literal(PRESENCE_SCHEMA),
  device: DeviceId,
  actor: ActorId,
  name: PersonName,
  initials: Initials,
  at: IsoTime,
  hlc: Hlc.optional(),
  open: CollabTarget.optional(),
});
export const PackageReplyPolicy = z.object({
  teamProjectId: TeamProjectId,
  ownerKey: PublicKeyB64,
  comments: z.boolean(),
  acceptance: z.boolean(),
});
export const EXCHANGE_MAX_BYTES = 2 * 1024 * 1024 * 1024;
export const EXCHANGE_ENVELOPE_SCHEMA = 'aio.exchange-enc/1';
export const ExchangeEnvelope = z.looseObject({
  schema: z.literal(EXCHANGE_ENVELOPE_SCHEMA),
  kdf: z.literal('scrypt'),
  cipher: z.literal('aes-256-gcm'),
  N: z.number().int().positive(),
  r: z.number().int().positive(),
  p: z.number().int().positive(),
  salt: z.string().min(1).max(200),
  nonce: z.string().min(1).max(200),
  chunk: z.number().int().positive(),
});
