// Generated by tools/compat/extract-schema.mjs from packages/schema/src/identity.ts at 91770f2 (Stratlas 0.9). Do not edit.
import { z } from 'zod';
import { IsoTime, PublicKeyB64, SignatureB64 } from './common.mjs';
export const IDENTITY_SCHEMA = 'aio.identity/1';
export const DEVICE_SCHEMA = 'aio.device/1';
export const IDENTITY_CARD_SCHEMA = 'aio.idcard/1';
export const IDENTITY_FILE = 'identity.json';
export const IDENTITY_CARD_EXTENSION = '.aioid';
export const DEVICE_KEY_ACCOUNT = 'device-signing';
export const ActorId = z
  .string()
  .regex(/^a_[a-z2-7]{26}$/, 'An actor id is a_ and 26 base32 letters.');
export const DeviceId = z
  .string()
  .regex(/^d_[a-z2-7]{52}$/, 'A device id is d_ and 52 base32 letters.');
export const PersonName = z.string().trim().min(1).max(80);
export const Initials = z
  .string()
  .regex(/^\p{L}{1,3}\d?$/u, 'Initials are 1 to 3 letters, optionally followed by one digit.');
export const Email = z.email().max(254);
export const VerificationLevel = z.enum(['self', 'owner', 'server', 'account']);
export const VERIFICATION_ORDER = VerificationLevel.options;
export const Identity = z.object({
  schema: z.literal(IDENTITY_SCHEMA),
  actor: ActorId,
  name: PersonName,
  initials: Initials,
  email: Email.optional(),
  createdAt: IsoTime,
  migratedFrom: z.enum(['author-setting', 'os-account', 'new']).optional(),
});
export const AppStamp = z.object({
  name: z.string().min(1).max(80),
  version: z.string().min(1).max(40),
});
export const DeviceCert = z.object({
  level: VerificationLevel.exclude(['self']),
  issuer: z.object({
    actor: ActorId.optional(),
    device: z.string().min(1).max(128),
  }),
  actor: ActorId,
  device: DeviceId,
  issuedAt: IsoTime,
  expiresAt: IsoTime.optional(),
  sig: SignatureB64,
});
export const DeviceRecord = z.object({
  schema: z.literal(DEVICE_SCHEMA),
  id: DeviceId,
  alg: z.literal('ed25519'),
  key: PublicKeyB64,
  actor: ActorId,
  name: PersonName,
  initials: Initials,
  label: z.string().max(80).optional(),
  app: AppStamp,
  createdAt: IsoTime,
  certs: z.array(DeviceCert).default([]),
  sig: SignatureB64,
});
export const IdentityCard = z.object({
  schema: z.literal(IDENTITY_CARD_SCHEMA),
  actor: ActorId,
  name: PersonName,
  initials: Initials,
  email: Email.optional(),
  device: z.object({
    id: DeviceId,
    alg: z.literal('ed25519'),
    key: PublicKeyB64,
  }),
  app: AppStamp,
  createdAt: IsoTime,
  sig: SignatureB64,
});
export const Role = z.enum(['owner', 'reviewer', 'viewer', 'client']);
export const AccountLink = z.object({
  actor: ActorId,
  issuer: z.string().min(1).max(200),
  account: z.string().min(1).max(200),
  linkedAt: IsoTime,
  cert: z.string().min(1).max(8192),
});
export const Member = z.object({
  actor: ActorId,
  name: PersonName,
  initials: Initials,
  email: Email.optional(),
  role: Role,
  devices: z.array(
    z.object({
      id: DeviceId,
      key: PublicKeyB64,
      revoked: z.boolean(),
      revokedAt: z.string().optional(),
    }),
  ),
  verification: VerificationLevel,
  addedBy: ActorId,
  addedAt: z.string(),
  account: AccountLink.optional(),
  source: z.enum(['journal', 'server']).optional(),
  certifiedBy: ActorId.optional(),
});
export const Permission = z.enum([
  'read',
  'comment.team',
  'comment.client',
  'accept',
  'edit',
  'assign',
  'approve',
  'close-approved',
  'builder.edit',
  'builder.georef',
  'admin',
  'export.package',
  'export.audit',
  'verify',
]);
export const PERMISSIONS = {
  read: {
    roles: ['owner', 'reviewer', 'viewer', 'client'],
  },
  'comment.team': {
    roles: ['owner', 'reviewer'],
    policy: {
      switch: 'viewersMayComment',
      adds: 'viewer',
    },
  },
  'comment.client': {
    roles: ['owner', 'reviewer', 'client'],
  },
  accept: {
    roles: ['owner', 'reviewer', 'client'],
  },
  edit: {
    roles: ['owner', 'reviewer'],
  },
  assign: {
    roles: ['owner', 'reviewer'],
  },
  approve: {
    roles: ['owner', 'reviewer'],
  },
  'close-approved': {
    roles: ['owner'],
    policy: {
      switch: 'closeBy',
      adds: 'reviewer',
    },
  },
  'builder.edit': {
    roles: ['owner', 'reviewer'],
  },
  'builder.georef': {
    roles: ['owner'],
  },
  admin: {
    roles: ['owner'],
  },
  'export.package': {
    roles: ['owner', 'reviewer'],
  },
  'export.audit': {
    roles: ['owner', 'reviewer', 'viewer'],
  },
  verify: {
    roles: ['owner', 'reviewer', 'viewer', 'client'],
  },
};
export const GEOREF_FIELDS = ['crs', 'origin', 'verticalDatum'];
export function rolesFor(permission, policy) {
  const rule = PERMISSIONS[permission];
  const roles = [...rule.roles];
  const extra = rule.policy;
  if (extra) {
    const on =
      extra.switch === 'viewersMayComment'
        ? policy.approval.viewersMayComment
        : policy.approval.closeBy === 'owner-or-reviewer';
    if (on && !roles.includes(extra.adds)) roles.push(extra.adds);
  }
  return roles;
}
export function permits(role, permission, policy) {
  return rolesFor(permission, policy).includes(role);
}
const ROLE_ARTICLES = {
  owner: 'an owner',
  reviewer: 'a reviewer',
  viewer: 'a viewer',
  client: 'a client',
};
const PERMISSION_ACTIONS = {
  read: 'open the project',
  'comment.team': 'comment for the team',
  'comment.client': 'comment for the client',
  accept: 'record client acceptance',
  edit: 'edit',
  assign: 'assign work',
  approve: 'approve',
  'close-approved': 'close or reopen an approved issue',
  'builder.edit': 'change layers, imports and pipelines',
  'builder.georef': 'change the coordinate system, origin or datum',
  admin: 'change members, roles, devices and the team policy',
  'export.package': 'export a customer package',
  'export.audit': 'export the audit',
  verify: 'verify the history',
};
function listOr(items) {
  if (items.length <= 1) return items[0] ?? 'nobody';
  return `${items.slice(0, -1).join(', ')} or ${items[items.length - 1] ?? ''}`;
}
export function roleRefusal(name, role, permission, policy) {
  const who = listOr(rolesFor(permission, policy).map((r) => ROLE_ARTICLES[r]));
  return `${name} is ${ROLE_ARTICLES[role]} in this project. Only ${who} can ${PERMISSION_ACTIONS[permission]}.`;
}
export const MemberAddPayload = z.object({
  actor: ActorId,
  name: PersonName,
  initials: Initials,
  email: Email.optional(),
  role: Role,
  devices: z
    .array(
      z.object({
        id: DeviceId,
        key: PublicKeyB64,
      }),
    )
    .min(1),
  cert: DeviceCert.optional(),
});
export const MemberRolePayload = z.object({
  actor: ActorId,
  role: Role,
});
export const MemberRemovePayload = z.object({
  actor: ActorId,
});
export const MemberLinkPayload = AccountLink;
export const DeviceRevokePayload = z.object({
  device: DeviceId,
  reason: z.string().max(500).optional(),
});
export function verifiedAtLeast(level, min) {
  return VERIFICATION_ORDER.indexOf(level) >= VERIFICATION_ORDER.indexOf(min);
}
