// Generated by tools/compat/extract-schema.mjs from packages/schema/src/road.ts at 91770f2 (Stratlas 0.9). Do not edit.
import { z } from 'zod';
import { HexColor, Vec3, err, ok } from './common.mjs';
export const ROAD_SCHEMA = 'aio.road/1';
const BySeverity = z.object({
  low: z.number().nullable(),
  medium: z.number().nullable(),
  high: z.number().nullable(),
});
export const PciRating = z.object({
  min: z.number(),
  label: z.string().min(1),
  color: HexColor,
});
export const PciSection = z.object({
  fromKm: z.number(),
  toKm: z.number(),
  pavementM2: z.number().nullable(),
  pci: BySeverity,
});
export const PciUnit = z.object({
  id: z.string().min(1),
  pavementM2: z.number().nonnegative(),
  pci: BySeverity,
  km: z.number(),
  fromKm: z.number().optional(),
  toKm: z.number().optional(),
  deducts: z.array(
    z.object({
      distress: z.string().min(1),
      densityPct: z.number(),
      deduct: z.number(),
    }),
  ),
  cells: z.array(z.tuple([z.number().int(), z.number().int()])),
});
export const PciLayout = z.enum(['grid', 'chainage']);
export const DensityCell = z.object({
  i: z.number().int(),
  j: z.number().int(),
  pavementM2: z.number().nonnegative(),
  defects: z.number().int().nonnegative(),
  defectM2: z.number().nonnegative(),
  coverPct: z.number().nonnegative(),
});
export const RoadModel = z
  .object({
    schema: z.literal(ROAD_SCHEMA),
    name: z.string().min(1),
    centreline: z.object({
      points: z.array(Vec3).min(2),
      chainageKm: z.array(z.number()),
      lengthKm: z.number().nonnegative(),
    }),
    pci: z.object({
      standard: z.string().min(1),
      severities: z.array(z.string()),
      headline: z.enum(['low', 'medium', 'high']),
      network: BySeverity,
      coveragePct: z.number().optional(),
      ratings: z.array(PciRating).min(1),
      layout: PciLayout.optional(),
      grid: z.object({
        cellM: z.number().positive(),
        origin: Vec3,
      }),
      sections: z.array(PciSection),
      units: z.array(PciUnit),
    }),
    density: z.object({
      gridOrigin: Vec3,
      sizes: z.record(z.string().regex(/^\d+$/), z.array(DensityCell)),
    }),
    overlays: z.record(z.string(), z.string()).optional(),
  })
  .superRefine((r, ctx) => {
    if (r.centreline.chainageKm.length !== r.centreline.points.length) {
      ctx.addIssue({
        code: 'custom',
        message: `The centreline needs one chainage per vertex (${r.centreline.points.length} vertices, ${r.centreline.chainageKm.length} chainages)`,
        path: ['centreline', 'chainageKm'],
      });
    }
    if ((r.pci.layout ?? 'grid') === 'grid') {
      const i = r.pci.units.findIndex((u) => u.cells.length === 0);
      if (i >= 0)
        ctx.addIssue({
          code: 'custom',
          message: 'A grid sample unit needs at least one cell',
          path: ['pci', 'units', i, 'cells'],
        });
    }
  });
export function parseRoadModel(json) {
  if (typeof json !== 'object' || json === null) return err('Road model is not a JSON object.');
  const version = json.schema;
  if (typeof version === 'string' && version !== ROAD_SCHEMA && version.startsWith('aio.road/'))
    return err(`Road model was saved by a newer Stratlas (schema ${version}). Update the app.`);
  const r = RoadModel.safeParse(json);
  if (r.success) return ok(r.data);
  const first = r.error.issues[0];
  const where = first?.path.length ? ` at ${first.path.join('.')}` : '';
  return err(`Road model is invalid${where}: ${first?.message ?? 'unknown error'}`);
}
