// Generated by tools/compat/extract-schema.mjs from packages/schema/src/sync.ts at 91770f2 (Stratlas 0.9). Do not edit.
import { z } from 'zod';
import { FetchPolicy } from './blobs.mjs';
import { Hlc, IsoTime, Sha256Hex, SignatureB64 } from './common.mjs';
import { Heads, TeamProjectId } from './exchange.mjs';
import {
  ActorId,
  DeviceCert,
  DeviceId,
  DeviceRecord,
  IdentityCard,
  Initials,
  Member,
  PersonName,
  Role,
} from './identity.mjs';
import { ChainId, Op, OpId, RecordRef, ReplicaId, Seq } from './journal.mjs';
export const SYNC_PROTOCOL = 'aio.sync/1';
export const RECEIPT_SCHEMA = 'aio.receipt/1';
export const SyncMode = z.enum(['off', 'exchange', 'hub', 'server']);
export const HostingModel = z.object({
  modes: z.array(SyncMode).default(['off', 'exchange', 'hub', 'server']),
  server: z.enum(['off', 'preview', 'ga']).default('preview'),
  hosted: z.boolean().default(false),
});
export const DEFAULT_HOSTING = HostingModel.parse({});
export const ProjectTeamConfig = z.object({
  root: z.string().min(1),
  replicaId: ReplicaId,
  mode: SyncMode,
  teamProjectId: TeamProjectId.optional(),
  hubPath: z.string().min(1).optional(),
  serverId: z.string().min(1).max(64).optional(),
  fetch: z.record(z.string(), FetchPolicy).default({}),
  peers: z.record(DeviceId, Heads).default({}),
  journal: z.enum(['on', 'off']).default('on'),
  lastSync: IsoTime.optional(),
});
export const TEAM_CONFIG_SCHEMA = 'aio.team-config/1';
export const TeamConfigFile = z.object({
  schema: z.literal(TEAM_CONFIG_SCHEMA),
  projects: z.array(ProjectTeamConfig),
});
export const ByteRange = z.object({
  start: z.number().int().nonnegative(),
  end: z.number().int().positive(),
});
export const RefusalCode = z.enum([
  'schema',
  'hash',
  'signature',
  'chain',
  'gap',
  'role',
  'revoked',
  'non-member',
  'clock-ahead',
]);
export const Receipt = z.object({
  schema: z.literal(RECEIPT_SCHEMA),
  server: z.string().min(1).max(64),
  seq: Seq,
  op: OpId,
  prev: Sha256Hex.nullable(),
  at: IsoTime,
  id: Sha256Hex,
  sig: SignatureB64,
});
export const PushResult = z.object({
  accepted: z.array(OpId),
  duplicates: z.array(OpId),
  refused: z.array(
    z.object({
      id: z.string(),
      code: RefusalCode,
      message: z.string(),
    }),
  ),
  receipts: z.array(Receipt).default([]),
});
export const PullPage = z.object({
  ops: z.array(Op),
  cursor: z.string().max(4096).nullable(),
  more: z.boolean(),
});
export const SYNC_ROUTES = {
  health: '/v1/health',
  enrol: '/v1/enrol',
  heads: '/v1/projects/:id/heads',
  ops: '/v1/projects/:id/ops',
  members: '/v1/projects/:id/members',
  blob: '/v1/blobs/:sha256',
};
export const SIGNED_REQUEST_COMPONENTS = [
  '@method',
  '@target-uri',
  'content-digest',
  'x-aio-device',
  'x-aio-nonce',
];
export const HealthResponse = z.object({
  ok: z.boolean(),
  version: z.string(),
  protocol: z.object({
    min: z.number().int(),
    max: z.number().int(),
  }),
});
export const EnrolRequest = z.object({
  code: z.string().min(6).max(128),
  device: DeviceRecord,
  card: IdentityCard.optional(),
});
export const EnrolResponse = z.object({
  server: z.object({
    id: z.string().min(1).max(64),
    name: z.string(),
    version: z.string(),
    fingerprint: Sha256Hex,
  }),
  cert: DeviceCert,
  role: Role,
  projects: z.array(
    z.object({
      teamProjectId: TeamProjectId,
      name: z.string(),
    }),
  ),
});
export const HeadsResponse = z.object({
  project: TeamProjectId,
  heads: Heads,
});
export const PushOpsRequest = z.object({
  ops: z.array(Op).min(1).max(5000),
});
export const PushOpsResponse = PushResult;
export const PullOpsQuery = z.object({
  since: z.string().max(4096).optional(),
  limit: z.coerce.number().int().min(1).max(5000).optional(),
});
export const PullOpsResponse = PullPage;
export const MembersResponse = z.object({
  members: z.array(Member),
});
export const SyncErrorBody = z.object({
  error: z.string(),
  code: z.string(),
});
export const Conflict = z.object({
  id: z.string().min(1).max(300),
  target: RecordRef,
  field: z.string().min(1).max(100),
  ours: z.object({
    value: z.unknown(),
    by: ActorId,
    hlc: Hlc,
    op: OpId,
  }),
  theirs: z.object({
    value: z.unknown(),
    by: ActorId,
    hlc: Hlc,
    op: OpId,
  }),
  kind: z.enum(['value', 'delete-edit', 'status', 'code', 'merge']),
  current: z.enum(['ours', 'theirs']),
});
export const QuarantineEntry = z.object({
  op: OpId,
  chain: ChainId,
  seq: Seq,
  by: ActorId,
  device: DeviceId,
  hlc: Hlc,
  kind: z.string(),
  target: RecordRef,
  reason: RefusalCode,
  message: z.string(),
});
export const TeamStatus = z.object({
  mode: SyncMode,
  teamProjectId: TeamProjectId.optional(),
  name: z.string().optional(),
  role: Role.optional(),
  lastSync: IsoTime.optional(),
  pending: z.number().int().nonnegative(),
  conflicts: z.number().int().nonnegative(),
  quarantined: z.number().int().nonnegative(),
  unread: z.number().int().nonnegative(),
  reachable: z.boolean().optional(),
  online: z
    .array(
      z.object({
        actor: ActorId,
        name: PersonName,
        initials: Initials,
        at: IsoTime,
      }),
    )
    .optional(),
});
export const ServerInfo = z.object({
  id: z.string().min(1).max(64),
  url: z.url({
    protocol: /^https$/,
  }),
  name: z.string(),
  fingerprint: Sha256Hex,
  version: z.string().optional(),
  enrolledAt: IsoTime,
  role: Role.optional(),
  reachable: z.boolean().optional(),
  checkedAt: IsoTime.optional(),
});
